//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * AddressWithDeliverability element
 * 
 * <p>Java class for AddressWithDeliverability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressWithDeliverability"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="address" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}AddressDescription"/&gt;
 *         &lt;element name="deliverability" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Deliverability"/&gt;
 *         &lt;element name="addressInputDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="addressId" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Identifier"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressWithDeliverability", propOrder = {

})
public class AddressWithDeliverability {

    @XmlElement(required = true)
    protected AddressDescription address;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Deliverability deliverability;
    @XmlElement(required = true)
    protected String addressInputDate;
    @XmlElement(required = true)
    protected Identifier addressId;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDescription }
     *     
     */
    public AddressDescription getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDescription }
     *     
     */
    public void setAddress(AddressDescription value) {
        this.address = value;
    }

    /**
     * Gets the value of the deliverability property.
     * 
     * @return
     *     possible object is
     *     {@link Deliverability }
     *     
     */
    public Deliverability getDeliverability() {
        return deliverability;
    }

    /**
     * Sets the value of the deliverability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Deliverability }
     *     
     */
    public void setDeliverability(Deliverability value) {
        this.deliverability = value;
    }

    /**
     * Gets the value of the addressInputDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressInputDate() {
        return addressInputDate;
    }

    /**
     * Sets the value of the addressInputDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressInputDate(String value) {
        this.addressInputDate = value;
    }

    /**
     * Gets the value of the addressId property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getAddressId() {
        return addressId;
    }

    /**
     * Sets the value of the addressId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setAddressId(Identifier value) {
        this.addressId = value;
    }

}
