//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * BusinessIndustryLicense element
 * 
 * <p>Java class for BusinessIndustryLicense complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessIndustryLicense"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="industryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="industryCode" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}IndustryCode" minOccurs="0"/&gt;
 *         &lt;element name="issuedTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="period" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Period" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}BusinessIndustryLicenseStatus"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessIndustryLicense", propOrder = {
    "industryName",
    "industryCode",
    "issuedTo",
    "period",
    "status"
})
public class BusinessIndustryLicense {

    @XmlElement(required = true)
    protected String industryName;
    protected IndustryCode industryCode;
    protected String issuedTo;
    protected Period period;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected BusinessIndustryLicenseStatus status;

    /**
     * Gets the value of the industryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustryName() {
        return industryName;
    }

    /**
     * Sets the value of the industryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustryName(String value) {
        this.industryName = value;
    }

    /**
     * Gets the value of the industryCode property.
     * 
     * @return
     *     possible object is
     *     {@link IndustryCode }
     *     
     */
    public IndustryCode getIndustryCode() {
        return industryCode;
    }

    /**
     * Sets the value of the industryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndustryCode }
     *     
     */
    public void setIndustryCode(IndustryCode value) {
        this.industryCode = value;
    }

    /**
     * Gets the value of the issuedTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuedTo() {
        return issuedTo;
    }

    /**
     * Sets the value of the issuedTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuedTo(String value) {
        this.issuedTo = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setPeriod(Period value) {
        this.period = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessIndustryLicenseStatus }
     *     
     */
    public BusinessIndustryLicenseStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessIndustryLicenseStatus }
     *     
     */
    public void setStatus(BusinessIndustryLicenseStatus value) {
        this.status = value;
    }

}
