//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CharacterType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CharacterType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="IDENTITY"/&gt;
 *     &lt;enumeration value="IDENTITY_WITH_CONFLICTING_HOUSE"/&gt;
 *     &lt;enumeration value="IDENTITY_WITH_CONFLICTING_STREET"/&gt;
 *     &lt;enumeration value="IDENTITY_WITH_CONFLICTING_CITY"/&gt;
 *     &lt;enumeration value="LAST_NAME_IN_HOUSE"/&gt;
 *     &lt;enumeration value="HOUSE_CONFIRMED"/&gt;
 *     &lt;enumeration value="STREET_CONFIRMED"/&gt;
 *     &lt;enumeration value="CITY_CONFIRMED"/&gt;
 *     &lt;enumeration value="NOT_CONFIRMED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CharacterType")
@XmlEnum
public enum CharacterType {

    IDENTITY,
    IDENTITY_WITH_CONFLICTING_HOUSE,
    IDENTITY_WITH_CONFLICTING_STREET,
    IDENTITY_WITH_CONFLICTING_CITY,
    LAST_NAME_IN_HOUSE,
    HOUSE_CONFIRMED,
    STREET_CONFIRMED,
    CITY_CONFIRMED,
    NOT_CONFIRMED;

    public String value() {
        return name();
    }

    public static CharacterType fromValue(String v) {
        return valueOf(v);
    }

}
