//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * CompanyHistoryItemActivityStatus element
 * 
 * <p>Java class for CompanyHistoryItemActivityStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyHistoryItemActivityStatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}CompanyHistoryItem"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="activityStatus" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}ActivityStatus"/&gt;
 *         &lt;element name="activityStatusOriginal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyHistoryItemActivityStatus", propOrder = {
    "activityStatus",
    "activityStatusOriginal"
})
public class CompanyHistoryItemActivityStatus
    extends CompanyHistoryItem
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ActivityStatus activityStatus;
    protected String activityStatusOriginal;

    /**
     * Gets the value of the activityStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityStatus }
     *     
     */
    public ActivityStatus getActivityStatus() {
        return activityStatus;
    }

    /**
     * Sets the value of the activityStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityStatus }
     *     
     */
    public void setActivityStatus(ActivityStatus value) {
        this.activityStatus = value;
    }

    /**
     * Gets the value of the activityStatusOriginal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityStatusOriginal() {
        return activityStatusOriginal;
    }

    /**
     * Sets the value of the activityStatusOriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityStatusOriginal(String value) {
        this.activityStatusOriginal = value;
    }

}
