//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ComplianceFoundEntity element
 * 
 * <p>Java class for ComplianceFoundEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplianceFoundEntity"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="listDescription" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}ComplianceListDescription"/&gt;
 *         &lt;element name="matchInformation" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}ComplianceMatchInformation"/&gt;
 *         &lt;element name="crifRefId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="primaryName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="furtherNames" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="birthdates" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="titles" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="furtherCountries" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="birthplaces" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="passportsOrIds" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="knownAddresses" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="keywords" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="additionalInformations" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplianceFoundEntity", propOrder = {
    "listDescription",
    "matchInformation",
    "crifRefId",
    "primaryName",
    "furtherNames",
    "birthdates",
    "age",
    "titles",
    "country",
    "furtherCountries",
    "birthplaces",
    "passportsOrIds",
    "knownAddresses",
    "keywords",
    "additionalInformations"
})
public class ComplianceFoundEntity {

    @XmlElement(required = true)
    protected ComplianceListDescription listDescription;
    @XmlElement(required = true)
    protected ComplianceMatchInformation matchInformation;
    protected int crifRefId;
    @XmlElement(required = true)
    protected String primaryName;
    protected List<String> furtherNames;
    protected List<String> birthdates;
    protected String age;
    protected List<String> titles;
    protected String country;
    protected List<String> furtherCountries;
    protected List<String> birthplaces;
    protected List<String> passportsOrIds;
    protected List<String> knownAddresses;
    protected List<String> keywords;
    protected List<String> additionalInformations;

    /**
     * Gets the value of the listDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ComplianceListDescription }
     *     
     */
    public ComplianceListDescription getListDescription() {
        return listDescription;
    }

    /**
     * Sets the value of the listDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplianceListDescription }
     *     
     */
    public void setListDescription(ComplianceListDescription value) {
        this.listDescription = value;
    }

    /**
     * Gets the value of the matchInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ComplianceMatchInformation }
     *     
     */
    public ComplianceMatchInformation getMatchInformation() {
        return matchInformation;
    }

    /**
     * Sets the value of the matchInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplianceMatchInformation }
     *     
     */
    public void setMatchInformation(ComplianceMatchInformation value) {
        this.matchInformation = value;
    }

    /**
     * Gets the value of the crifRefId property.
     * 
     */
    public int getCrifRefId() {
        return crifRefId;
    }

    /**
     * Sets the value of the crifRefId property.
     * 
     */
    public void setCrifRefId(int value) {
        this.crifRefId = value;
    }

    /**
     * Gets the value of the primaryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryName() {
        return primaryName;
    }

    /**
     * Sets the value of the primaryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryName(String value) {
        this.primaryName = value;
    }

    /**
     * Gets the value of the furtherNames property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the furtherNames property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFurtherNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFurtherNames() {
        if (furtherNames == null) {
            furtherNames = new ArrayList<String>();
        }
        return this.furtherNames;
    }

    /**
     * Gets the value of the birthdates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the birthdates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBirthdates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBirthdates() {
        if (birthdates == null) {
            birthdates = new ArrayList<String>();
        }
        return this.birthdates;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAge(String value) {
        this.age = value;
    }

    /**
     * Gets the value of the titles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTitles() {
        if (titles == null) {
            titles = new ArrayList<String>();
        }
        return this.titles;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the furtherCountries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the furtherCountries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFurtherCountries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFurtherCountries() {
        if (furtherCountries == null) {
            furtherCountries = new ArrayList<String>();
        }
        return this.furtherCountries;
    }

    /**
     * Gets the value of the birthplaces property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the birthplaces property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBirthplaces().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBirthplaces() {
        if (birthplaces == null) {
            birthplaces = new ArrayList<String>();
        }
        return this.birthplaces;
    }

    /**
     * Gets the value of the passportsOrIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passportsOrIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassportsOrIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPassportsOrIds() {
        if (passportsOrIds == null) {
            passportsOrIds = new ArrayList<String>();
        }
        return this.passportsOrIds;
    }

    /**
     * Gets the value of the knownAddresses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the knownAddresses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKnownAddresses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getKnownAddresses() {
        if (knownAddresses == null) {
            knownAddresses = new ArrayList<String>();
        }
        return this.knownAddresses;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keywords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeywords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getKeywords() {
        if (keywords == null) {
            keywords = new ArrayList<String>();
        }
        return this.keywords;
    }

    /**
     * Gets the value of the additionalInformations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInformations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInformations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAdditionalInformations() {
        if (additionalInformations == null) {
            additionalInformations = new ArrayList<String>();
        }
        return this.additionalInformations;
    }

}
