//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ComplianceCheckedEntity element
 * 
 * <p>Java class for ComplianceCheckedEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplianceCheckedEntity"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="checkedAddress" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}AddressDescription"/&gt;
 *         &lt;element name="relationType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="foundEntities" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}ComplianceFoundEntity" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="checkedEntities" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}ComplianceCheckedEntity" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplianceCheckedEntity", propOrder = {
    "checkedAddress",
    "relationType",
    "foundEntities",
    "checkedEntities"
})
public class ComplianceCheckedEntity {

    @XmlElement(required = true)
    protected AddressDescription checkedAddress;
    @XmlElement(required = true)
    protected String relationType;
    protected List<ComplianceFoundEntity> foundEntities;
    protected List<ComplianceCheckedEntity> checkedEntities;

    /**
     * Gets the value of the checkedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDescription }
     *     
     */
    public AddressDescription getCheckedAddress() {
        return checkedAddress;
    }

    /**
     * Sets the value of the checkedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDescription }
     *     
     */
    public void setCheckedAddress(AddressDescription value) {
        this.checkedAddress = value;
    }

    /**
     * Gets the value of the relationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationType() {
        return relationType;
    }

    /**
     * Sets the value of the relationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationType(String value) {
        this.relationType = value;
    }

    /**
     * Gets the value of the foundEntities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the foundEntities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFoundEntities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplianceFoundEntity }
     * 
     * 
     */
    public List<ComplianceFoundEntity> getFoundEntities() {
        if (foundEntities == null) {
            foundEntities = new ArrayList<ComplianceFoundEntity>();
        }
        return this.foundEntities;
    }

    /**
     * Gets the value of the checkedEntities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the checkedEntities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCheckedEntities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplianceCheckedEntity }
     * 
     * 
     */
    public List<ComplianceCheckedEntity> getCheckedEntities() {
        if (checkedEntities == null) {
            checkedEntities = new ArrayList<ComplianceCheckedEntity>();
        }
        return this.checkedEntities;
    }

}
