//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * ComplianceMatchInformation element
 * 
 * <p>Java class for ComplianceMatchInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplianceMatchInformation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="confidenceName" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="confidenceBirthdate" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="matchedName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="matchedBirthdate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplianceMatchInformation", propOrder = {
    "confidenceName",
    "confidenceBirthdate",
    "matchedName",
    "matchedBirthdate"
})
public class ComplianceMatchInformation {

    protected int confidenceName;
    protected int confidenceBirthdate;
    protected String matchedName;
    protected String matchedBirthdate;

    /**
     * Gets the value of the confidenceName property.
     * 
     */
    public int getConfidenceName() {
        return confidenceName;
    }

    /**
     * Sets the value of the confidenceName property.
     * 
     */
    public void setConfidenceName(int value) {
        this.confidenceName = value;
    }

    /**
     * Gets the value of the confidenceBirthdate property.
     * 
     */
    public int getConfidenceBirthdate() {
        return confidenceBirthdate;
    }

    /**
     * Sets the value of the confidenceBirthdate property.
     * 
     */
    public void setConfidenceBirthdate(int value) {
        this.confidenceBirthdate = value;
    }

    /**
     * Gets the value of the matchedName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchedName() {
        return matchedName;
    }

    /**
     * Sets the value of the matchedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchedName(String value) {
        this.matchedName = value;
    }

    /**
     * Gets the value of the matchedBirthdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchedBirthdate() {
        return matchedBirthdate;
    }

    /**
     * Sets the value of the matchedBirthdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchedBirthdate(String value) {
        this.matchedBirthdate = value;
    }

}
