//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * CompanyHistoryItem element
 * 
 * <p>Java class for CompanyHistoryItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyHistoryItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="type" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}CompanyHistoryItemType"/&gt;
 *         &lt;element name="period" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Period"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyHistoryItem", propOrder = {
    "type",
    "period"
})
@XmlSeeAlso({
    CompanyHistoryItemActivityStatus.class,
    CompanyHistoryItemAddress.class,
    CompanyHistoryItemAmount.class,
    CompanyHistoryItemLegalForm.class,
    CompanyHistoryItemLocation.class,
    CompanyHistoryItemText.class
})
public class CompanyHistoryItem {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CompanyHistoryItemType type;
    @XmlElement(required = true)
    protected Period period;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyHistoryItemType }
     *     
     */
    public CompanyHistoryItemType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyHistoryItemType }
     *     
     */
    public void setType(CompanyHistoryItemType value) {
        this.type = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setPeriod(Period value) {
        this.period = value;
    }

}
