//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * CompanyHistoryItemLegalForm element
 * 
 * <p>Java class for CompanyHistoryItemLegalForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyHistoryItemLegalForm"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}CompanyHistoryItem"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="legalFormType" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}LegalFormType"/&gt;
 *         &lt;element name="legalFormTypeOriginal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="legalFormText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyHistoryItemLegalForm", propOrder = {
    "legalFormType",
    "legalFormTypeOriginal",
    "legalFormText"
})
public class CompanyHistoryItemLegalForm
    extends CompanyHistoryItem
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected LegalFormType legalFormType;
    protected String legalFormTypeOriginal;
    protected String legalFormText;

    /**
     * Gets the value of the legalFormType property.
     * 
     * @return
     *     possible object is
     *     {@link LegalFormType }
     *     
     */
    public LegalFormType getLegalFormType() {
        return legalFormType;
    }

    /**
     * Sets the value of the legalFormType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalFormType }
     *     
     */
    public void setLegalFormType(LegalFormType value) {
        this.legalFormType = value;
    }

    /**
     * Gets the value of the legalFormTypeOriginal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalFormTypeOriginal() {
        return legalFormTypeOriginal;
    }

    /**
     * Sets the value of the legalFormTypeOriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalFormTypeOriginal(String value) {
        this.legalFormTypeOriginal = value;
    }

    /**
     * Gets the value of the legalFormText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalFormText() {
        return legalFormText;
    }

    /**
     * Sets the value of the legalFormText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalFormText(String value) {
        this.legalFormText = value;
    }

}
