//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * ControlPerson element
 * 
 * <p>Java class for ControlPerson complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ControlPerson"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="controlPersonAddress" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}AddressDescription"/&gt;
 *         &lt;element name="controlPersonType" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}ControlPersonType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ControlPerson", propOrder = {
    "controlPersonAddress",
    "controlPersonType"
})
public class ControlPerson {

    @XmlElement(required = true)
    protected AddressDescription controlPersonAddress;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ControlPersonType controlPersonType;

    /**
     * Gets the value of the controlPersonAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDescription }
     *     
     */
    public AddressDescription getControlPersonAddress() {
        return controlPersonAddress;
    }

    /**
     * Sets the value of the controlPersonAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDescription }
     *     
     */
    public void setControlPersonAddress(AddressDescription value) {
        this.controlPersonAddress = value;
    }

    /**
     * Gets the value of the controlPersonType property.
     * 
     * @return
     *     possible object is
     *     {@link ControlPersonType }
     *     
     */
    public ControlPersonType getControlPersonType() {
        return controlPersonType;
    }

    /**
     * Sets the value of the controlPersonType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlPersonType }
     *     
     */
    public void setControlPersonType(ControlPersonType value) {
        this.controlPersonType = value;
    }

}
