//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * DebtEntry element
 * 
 * <p>Java class for DebtEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DebtEntry"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="riskClass" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}RiskClass"/&gt;
 *         &lt;element name="dateOpen" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dateClose" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="amount" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Amount" minOccurs="0"/&gt;
 *         &lt;element name="amountOpen" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Amount" minOccurs="0"/&gt;
 *         &lt;element name="debtType" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}DebtType"/&gt;
 *         &lt;element name="paymentStatus" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}PaymentStatus"/&gt;
 *         &lt;element name="paymentStatusText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DebtEntry", propOrder = {

})
public class DebtEntry {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected RiskClass riskClass;
    @XmlElement(required = true)
    protected String dateOpen;
    protected String dateClose;
    protected Amount amount;
    protected Amount amountOpen;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected DebtType debtType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PaymentStatus paymentStatus;
    @XmlElement(required = true)
    protected String paymentStatusText;
    protected String origin;
    protected String text;

    /**
     * Gets the value of the riskClass property.
     * 
     * @return
     *     possible object is
     *     {@link RiskClass }
     *     
     */
    public RiskClass getRiskClass() {
        return riskClass;
    }

    /**
     * Sets the value of the riskClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiskClass }
     *     
     */
    public void setRiskClass(RiskClass value) {
        this.riskClass = value;
    }

    /**
     * Gets the value of the dateOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOpen() {
        return dateOpen;
    }

    /**
     * Sets the value of the dateOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOpen(String value) {
        this.dateOpen = value;
    }

    /**
     * Gets the value of the dateClose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateClose() {
        return dateClose;
    }

    /**
     * Sets the value of the dateClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateClose(String value) {
        this.dateClose = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAmount(Amount value) {
        this.amount = value;
    }

    /**
     * Gets the value of the amountOpen property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAmountOpen() {
        return amountOpen;
    }

    /**
     * Sets the value of the amountOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAmountOpen(Amount value) {
        this.amountOpen = value;
    }

    /**
     * Gets the value of the debtType property.
     * 
     * @return
     *     possible object is
     *     {@link DebtType }
     *     
     */
    public DebtType getDebtType() {
        return debtType;
    }

    /**
     * Sets the value of the debtType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebtType }
     *     
     */
    public void setDebtType(DebtType value) {
        this.debtType = value;
    }

    /**
     * Gets the value of the paymentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentStatus }
     *     
     */
    public PaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Sets the value of the paymentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentStatus }
     *     
     */
    public void setPaymentStatus(PaymentStatus value) {
        this.paymentStatus = value;
    }

    /**
     * Gets the value of the paymentStatusText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentStatusText() {
        return paymentStatusText;
    }

    /**
     * Sets the value of the paymentStatusText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentStatusText(String value) {
        this.paymentStatusText = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

}
