//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * DecisionMatrix element
 * 
 * <p>Java class for DecisionMatrix complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecisionMatrix"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="decision" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Decision"/&gt;
 *         &lt;element name="decisionText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="subdecisions" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Subdecision" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ratings" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Rating" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="creditLimit" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecisionMatrix", propOrder = {
    "decision",
    "decisionText",
    "subdecisions",
    "ratings",
    "creditLimit"
})
public class DecisionMatrix {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Decision decision;
    @XmlElement(required = true)
    protected String decisionText;
    protected List<Subdecision> subdecisions;
    protected List<Rating> ratings;
    protected BigInteger creditLimit;

    /**
     * Gets the value of the decision property.
     * 
     * @return
     *     possible object is
     *     {@link Decision }
     *     
     */
    public Decision getDecision() {
        return decision;
    }

    /**
     * Sets the value of the decision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Decision }
     *     
     */
    public void setDecision(Decision value) {
        this.decision = value;
    }

    /**
     * Gets the value of the decisionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecisionText() {
        return decisionText;
    }

    /**
     * Sets the value of the decisionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecisionText(String value) {
        this.decisionText = value;
    }

    /**
     * Gets the value of the subdecisions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subdecisions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubdecisions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subdecision }
     * 
     * 
     */
    public List<Subdecision> getSubdecisions() {
        if (subdecisions == null) {
            subdecisions = new ArrayList<Subdecision>();
        }
        return this.subdecisions;
    }

    /**
     * Gets the value of the ratings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ratings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRatings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rating }
     * 
     * 
     */
    public List<Rating> getRatings() {
        if (ratings == null) {
            ratings = new ArrayList<Rating>();
        }
        return this.ratings;
    }

    /**
     * Gets the value of the creditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCreditLimit() {
        return creditLimit;
    }

    /**
     * Sets the value of the creditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCreditLimit(BigInteger value) {
        this.creditLimit = value;
    }

}
