//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ESchKgOrderData element
 * 
 * <p>Java class for ESchKgOrderData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ESchKgOrderData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="orderId" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="referenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="externalId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="caseGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="caseGroupType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="representative" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="address" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}AddressDescription"/&gt;
 *         &lt;element name="jobList" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}jobList"/&gt;
 *         &lt;element name="claimList" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}claimList"/&gt;
 *         &lt;element name="statusMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="officeCaseNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="officeStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="deadlineFrom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="deadlineTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ESchKgOrderData", propOrder = {
    "orderId",
    "referenceNumber",
    "externalId",
    "caseGroup",
    "caseGroupType",
    "representative",
    "address",
    "jobList",
    "claimList",
    "statusMessage",
    "officeCaseNumber",
    "officeStatus",
    "deadlineFrom",
    "deadlineTo"
})
public class ESchKgOrderData {

    @XmlElement(required = true)
    protected BigInteger orderId;
    protected String referenceNumber;
    protected String externalId;
    protected String caseGroup;
    protected String caseGroupType;
    protected String representative;
    @XmlElement(required = true)
    protected AddressDescription address;
    @XmlElement(required = true)
    protected JobList jobList;
    @XmlElement(required = true)
    protected ClaimList claimList;
    protected String statusMessage;
    protected String officeCaseNumber;
    protected String officeStatus;
    protected String deadlineFrom;
    protected String deadlineTo;

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderId(BigInteger value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the referenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * Sets the value of the referenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceNumber(String value) {
        this.referenceNumber = value;
    }

    /**
     * Gets the value of the externalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalId() {
        return externalId;
    }

    /**
     * Sets the value of the externalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalId(String value) {
        this.externalId = value;
    }

    /**
     * Gets the value of the caseGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseGroup() {
        return caseGroup;
    }

    /**
     * Sets the value of the caseGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseGroup(String value) {
        this.caseGroup = value;
    }

    /**
     * Gets the value of the caseGroupType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseGroupType() {
        return caseGroupType;
    }

    /**
     * Sets the value of the caseGroupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseGroupType(String value) {
        this.caseGroupType = value;
    }

    /**
     * Gets the value of the representative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentative() {
        return representative;
    }

    /**
     * Sets the value of the representative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentative(String value) {
        this.representative = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDescription }
     *     
     */
    public AddressDescription getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDescription }
     *     
     */
    public void setAddress(AddressDescription value) {
        this.address = value;
    }

    /**
     * Gets the value of the jobList property.
     * 
     * @return
     *     possible object is
     *     {@link JobList }
     *     
     */
    public JobList getJobList() {
        return jobList;
    }

    /**
     * Sets the value of the jobList property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobList }
     *     
     */
    public void setJobList(JobList value) {
        this.jobList = value;
    }

    /**
     * Gets the value of the claimList property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimList }
     *     
     */
    public ClaimList getClaimList() {
        return claimList;
    }

    /**
     * Sets the value of the claimList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimList }
     *     
     */
    public void setClaimList(ClaimList value) {
        this.claimList = value;
    }

    /**
     * Gets the value of the statusMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusMessage() {
        return statusMessage;
    }

    /**
     * Sets the value of the statusMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusMessage(String value) {
        this.statusMessage = value;
    }

    /**
     * Gets the value of the officeCaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficeCaseNumber() {
        return officeCaseNumber;
    }

    /**
     * Sets the value of the officeCaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficeCaseNumber(String value) {
        this.officeCaseNumber = value;
    }

    /**
     * Gets the value of the officeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficeStatus() {
        return officeStatus;
    }

    /**
     * Sets the value of the officeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficeStatus(String value) {
        this.officeStatus = value;
    }

    /**
     * Gets the value of the deadlineFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeadlineFrom() {
        return deadlineFrom;
    }

    /**
     * Sets the value of the deadlineFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeadlineFrom(String value) {
        this.deadlineFrom = value;
    }

    /**
     * Gets the value of the deadlineTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeadlineTo() {
        return deadlineTo;
    }

    /**
     * Sets the value of the deadlineTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeadlineTo(String value) {
        this.deadlineTo = value;
    }

}
