//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * FinancialBalance element
 * 
 * <p>Java class for FinancialStatement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FinancialStatement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="financialReportingStandard" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="currencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="period" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Period"/&gt;
 *         &lt;element name="balanceSheet" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}FinancialStatementElement" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="profitAndLoss" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}FinancialStatementElement" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="cashFlow" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}FinancialStatementElement" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="furtherFigures" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}FinancialStatementElement" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="creditRatios" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}CreditRatio" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FinancialStatement", propOrder = {
    "financialReportingStandard",
    "companyName",
    "currencyCode",
    "period",
    "balanceSheet",
    "profitAndLoss",
    "cashFlow",
    "furtherFigures",
    "creditRatios"
})
public class FinancialStatement {

    @XmlElement(required = true)
    protected String financialReportingStandard;
    @XmlElement(required = true)
    protected String companyName;
    @XmlElement(required = true)
    protected String currencyCode;
    @XmlElement(required = true)
    protected Period period;
    protected List<FinancialStatementElement> balanceSheet;
    protected List<FinancialStatementElement> profitAndLoss;
    protected List<FinancialStatementElement> cashFlow;
    protected List<FinancialStatementElement> furtherFigures;
    protected List<CreditRatio> creditRatios;

    /**
     * Gets the value of the financialReportingStandard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancialReportingStandard() {
        return financialReportingStandard;
    }

    /**
     * Sets the value of the financialReportingStandard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancialReportingStandard(String value) {
        this.financialReportingStandard = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setPeriod(Period value) {
        this.period = value;
    }

    /**
     * Gets the value of the balanceSheet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the balanceSheet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBalanceSheet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinancialStatementElement }
     * 
     * 
     */
    public List<FinancialStatementElement> getBalanceSheet() {
        if (balanceSheet == null) {
            balanceSheet = new ArrayList<FinancialStatementElement>();
        }
        return this.balanceSheet;
    }

    /**
     * Gets the value of the profitAndLoss property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profitAndLoss property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfitAndLoss().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinancialStatementElement }
     * 
     * 
     */
    public List<FinancialStatementElement> getProfitAndLoss() {
        if (profitAndLoss == null) {
            profitAndLoss = new ArrayList<FinancialStatementElement>();
        }
        return this.profitAndLoss;
    }

    /**
     * Gets the value of the cashFlow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cashFlow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCashFlow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinancialStatementElement }
     * 
     * 
     */
    public List<FinancialStatementElement> getCashFlow() {
        if (cashFlow == null) {
            cashFlow = new ArrayList<FinancialStatementElement>();
        }
        return this.cashFlow;
    }

    /**
     * Gets the value of the furtherFigures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the furtherFigures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFurtherFigures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinancialStatementElement }
     * 
     * 
     */
    public List<FinancialStatementElement> getFurtherFigures() {
        if (furtherFigures == null) {
            furtherFigures = new ArrayList<FinancialStatementElement>();
        }
        return this.furtherFigures;
    }

    /**
     * Gets the value of the creditRatios property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditRatios property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreditRatios().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreditRatio }
     * 
     * 
     */
    public List<CreditRatio> getCreditRatios() {
        if (creditRatios == null) {
            creditRatios = new ArrayList<CreditRatio>();
        }
        return this.creditRatios;
    }

}
