//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * FurtherRelations element
 * 
 * <p>Java class for FurtherRelations complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FurtherRelations"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="obviousRelations" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}CompanyBaseData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="probableRelations" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}CompanyBaseData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="samePhoneNumber" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}CompanyBaseData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FurtherRelations", propOrder = {
    "obviousRelations",
    "probableRelations",
    "samePhoneNumber"
})
public class FurtherRelations {

    protected List<CompanyBaseData> obviousRelations;
    protected List<CompanyBaseData> probableRelations;
    protected List<CompanyBaseData> samePhoneNumber;

    /**
     * Gets the value of the obviousRelations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the obviousRelations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObviousRelations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompanyBaseData }
     * 
     * 
     */
    public List<CompanyBaseData> getObviousRelations() {
        if (obviousRelations == null) {
            obviousRelations = new ArrayList<CompanyBaseData>();
        }
        return this.obviousRelations;
    }

    /**
     * Gets the value of the probableRelations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the probableRelations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProbableRelations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompanyBaseData }
     * 
     * 
     */
    public List<CompanyBaseData> getProbableRelations() {
        if (probableRelations == null) {
            probableRelations = new ArrayList<CompanyBaseData>();
        }
        return this.probableRelations;
    }

    /**
     * Gets the value of the samePhoneNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the samePhoneNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSamePhoneNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompanyBaseData }
     * 
     * 
     */
    public List<CompanyBaseData> getSamePhoneNumber() {
        if (samePhoneNumber == null) {
            samePhoneNumber = new ArrayList<CompanyBaseData>();
        }
        return this.samePhoneNumber;
    }

}
