//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IdentifierType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IdentifierType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ADDRESS_ID"/&gt;
 *     &lt;enumeration value="UNIT_ID"/&gt;
 *     &lt;enumeration value="LIABLE_ID"/&gt;
 *     &lt;enumeration value="CH_NUMBER"/&gt;
 *     &lt;enumeration value="CH_UID"/&gt;
 *     &lt;enumeration value="AT_FIRMENBUCHNUMMER"/&gt;
 *     &lt;enumeration value="CH_LEGACY_ADDRESS_ID"/&gt;
 *     &lt;enumeration value="CH_UID_VAT"/&gt;
 *     &lt;enumeration value="AT_UID"/&gt;
 *     &lt;enumeration value="AT_OENB"/&gt;
 *     &lt;enumeration value="AT_DVR_NR"/&gt;
 *     &lt;enumeration value="SCHUFA_ID"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "IdentifierType")
@XmlEnum
public enum IdentifierType {

    ADDRESS_ID,
    UNIT_ID,
    LIABLE_ID,
    CH_NUMBER,
    CH_UID,
    AT_FIRMENBUCHNUMMER,
    CH_LEGACY_ADDRESS_ID,
    CH_UID_VAT,
    AT_UID,
    AT_OENB,
    AT_DVR_NR,
    SCHUFA_ID;

    public String value() {
        return name();
    }

    public static IdentifierType fromValue(String v) {
        return valueOf(v);
    }

}
