//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * IdVerificationChecks element
 * 
 * <p>Java class for IdVerificationChecks complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdVerificationChecks"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isValid" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}NullableBoolean" minOccurs="0"/&gt;
 *         &lt;element name="isComplete" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}NullableBoolean" minOccurs="0"/&gt;
 *         &lt;element name="isCompositeCheckDigitVerified" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}NullableBoolean" minOccurs="0"/&gt;
 *         &lt;element name="isBirthDateVerified" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}NullableBoolean" minOccurs="0"/&gt;
 *         &lt;element name="isExpirationDateVerified" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}NullableBoolean" minOccurs="0"/&gt;
 *         &lt;element name="isDocumentNumberVerified" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}NullableBoolean" minOccurs="0"/&gt;
 *         &lt;element name="isIssuingStateOrOrganizationVerified" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}NullableBoolean" minOccurs="0"/&gt;
 *         &lt;element name="isNationalIdentificationNumberVerified" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}NullableBoolean" minOccurs="0"/&gt;
 *         &lt;element name="isNationalityVerified" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}NullableBoolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdVerificationChecks", propOrder = {
    "isValid",
    "isComplete",
    "isCompositeCheckDigitVerified",
    "isBirthDateVerified",
    "isExpirationDateVerified",
    "isDocumentNumberVerified",
    "isIssuingStateOrOrganizationVerified",
    "isNationalIdentificationNumberVerified",
    "isNationalityVerified"
})
public class IdVerificationChecks {

    @XmlSchemaType(name = "string")
    protected NullableBoolean isValid;
    @XmlSchemaType(name = "string")
    protected NullableBoolean isComplete;
    @XmlSchemaType(name = "string")
    protected NullableBoolean isCompositeCheckDigitVerified;
    @XmlSchemaType(name = "string")
    protected NullableBoolean isBirthDateVerified;
    @XmlSchemaType(name = "string")
    protected NullableBoolean isExpirationDateVerified;
    @XmlSchemaType(name = "string")
    protected NullableBoolean isDocumentNumberVerified;
    @XmlSchemaType(name = "string")
    protected NullableBoolean isIssuingStateOrOrganizationVerified;
    @XmlSchemaType(name = "string")
    protected NullableBoolean isNationalIdentificationNumberVerified;
    @XmlSchemaType(name = "string")
    protected NullableBoolean isNationalityVerified;

    /**
     * Gets the value of the isValid property.
     * 
     * @return
     *     possible object is
     *     {@link NullableBoolean }
     *     
     */
    public NullableBoolean getIsValid() {
        return isValid;
    }

    /**
     * Sets the value of the isValid property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullableBoolean }
     *     
     */
    public void setIsValid(NullableBoolean value) {
        this.isValid = value;
    }

    /**
     * Gets the value of the isComplete property.
     * 
     * @return
     *     possible object is
     *     {@link NullableBoolean }
     *     
     */
    public NullableBoolean getIsComplete() {
        return isComplete;
    }

    /**
     * Sets the value of the isComplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullableBoolean }
     *     
     */
    public void setIsComplete(NullableBoolean value) {
        this.isComplete = value;
    }

    /**
     * Gets the value of the isCompositeCheckDigitVerified property.
     * 
     * @return
     *     possible object is
     *     {@link NullableBoolean }
     *     
     */
    public NullableBoolean getIsCompositeCheckDigitVerified() {
        return isCompositeCheckDigitVerified;
    }

    /**
     * Sets the value of the isCompositeCheckDigitVerified property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullableBoolean }
     *     
     */
    public void setIsCompositeCheckDigitVerified(NullableBoolean value) {
        this.isCompositeCheckDigitVerified = value;
    }

    /**
     * Gets the value of the isBirthDateVerified property.
     * 
     * @return
     *     possible object is
     *     {@link NullableBoolean }
     *     
     */
    public NullableBoolean getIsBirthDateVerified() {
        return isBirthDateVerified;
    }

    /**
     * Sets the value of the isBirthDateVerified property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullableBoolean }
     *     
     */
    public void setIsBirthDateVerified(NullableBoolean value) {
        this.isBirthDateVerified = value;
    }

    /**
     * Gets the value of the isExpirationDateVerified property.
     * 
     * @return
     *     possible object is
     *     {@link NullableBoolean }
     *     
     */
    public NullableBoolean getIsExpirationDateVerified() {
        return isExpirationDateVerified;
    }

    /**
     * Sets the value of the isExpirationDateVerified property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullableBoolean }
     *     
     */
    public void setIsExpirationDateVerified(NullableBoolean value) {
        this.isExpirationDateVerified = value;
    }

    /**
     * Gets the value of the isDocumentNumberVerified property.
     * 
     * @return
     *     possible object is
     *     {@link NullableBoolean }
     *     
     */
    public NullableBoolean getIsDocumentNumberVerified() {
        return isDocumentNumberVerified;
    }

    /**
     * Sets the value of the isDocumentNumberVerified property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullableBoolean }
     *     
     */
    public void setIsDocumentNumberVerified(NullableBoolean value) {
        this.isDocumentNumberVerified = value;
    }

    /**
     * Gets the value of the isIssuingStateOrOrganizationVerified property.
     * 
     * @return
     *     possible object is
     *     {@link NullableBoolean }
     *     
     */
    public NullableBoolean getIsIssuingStateOrOrganizationVerified() {
        return isIssuingStateOrOrganizationVerified;
    }

    /**
     * Sets the value of the isIssuingStateOrOrganizationVerified property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullableBoolean }
     *     
     */
    public void setIsIssuingStateOrOrganizationVerified(NullableBoolean value) {
        this.isIssuingStateOrOrganizationVerified = value;
    }

    /**
     * Gets the value of the isNationalIdentificationNumberVerified property.
     * 
     * @return
     *     possible object is
     *     {@link NullableBoolean }
     *     
     */
    public NullableBoolean getIsNationalIdentificationNumberVerified() {
        return isNationalIdentificationNumberVerified;
    }

    /**
     * Sets the value of the isNationalIdentificationNumberVerified property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullableBoolean }
     *     
     */
    public void setIsNationalIdentificationNumberVerified(NullableBoolean value) {
        this.isNationalIdentificationNumberVerified = value;
    }

    /**
     * Gets the value of the isNationalityVerified property.
     * 
     * @return
     *     possible object is
     *     {@link NullableBoolean }
     *     
     */
    public NullableBoolean getIsNationalityVerified() {
        return isNationalityVerified;
    }

    /**
     * Sets the value of the isNationalityVerified property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullableBoolean }
     *     
     */
    public void setIsNationalityVerified(NullableBoolean value) {
        this.isNationalityVerified = value;
    }

}
