//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IdVerificationProcessingResult.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IdVerificationProcessingResult"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="REJECTED"/&gt;
 *     &lt;enumeration value="AUTOMATICLY_APPROVED"/&gt;
 *     &lt;enumeration value="MANUALY_APPROVED"/&gt;
 *     &lt;enumeration value="UNDETETERMINED"/&gt;
 *     &lt;enumeration value="PROCESSING_FAILED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "IdVerificationProcessingResult")
@XmlEnum
public enum IdVerificationProcessingResult {

    REJECTED,
    AUTOMATICLY_APPROVED,
    MANUALY_APPROVED,
    UNDETETERMINED,
    PROCESSING_FAILED;

    public String value() {
        return name();
    }

    public static IdVerificationProcessingResult fromValue(String v) {
        return valueOf(v);
    }

}
