//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LegalFormType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LegalFormType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SINGLE_PERSON_COMPANY"/&gt;
 *     &lt;enumeration value="MULTI_PERSON_COMPANY"/&gt;
 *     &lt;enumeration value="LIMITED_COMPANY"/&gt;
 *     &lt;enumeration value="PUBLIC"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LegalFormType")
@XmlEnum
public enum LegalFormType {

    SINGLE_PERSON_COMPANY,
    MULTI_PERSON_COMPANY,
    LIMITED_COMPANY,
    PUBLIC,
    OTHER;

    public String value() {
        return name();
    }

    public static LegalFormType fromValue(String v) {
        return valueOf(v);
    }

}
