//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocationIdentificationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LocationIdentificationType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="HOUSE_CONFIRMED"/&gt;
 *     &lt;enumeration value="STREET_CONFIRMED_HOUSE_NOT_PROVIDED"/&gt;
 *     &lt;enumeration value="STREET_CONFIRMED_HOUSE_NOT_IDENTIFIED"/&gt;
 *     &lt;enumeration value="CITY_CONFIRMED_STREET_NOT_PROVIDED"/&gt;
 *     &lt;enumeration value="CITY_CONFIRMED_STREET_NOT_IDENTIFIED"/&gt;
 *     &lt;enumeration value="NOT_CONFIRMED"/&gt;
 *     &lt;enumeration value="NOT_PROVIDED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LocationIdentificationType")
@XmlEnum
public enum LocationIdentificationType {

    HOUSE_CONFIRMED,
    STREET_CONFIRMED_HOUSE_NOT_PROVIDED,
    STREET_CONFIRMED_HOUSE_NOT_IDENTIFIED,
    CITY_CONFIRMED_STREET_NOT_PROVIDED,
    CITY_CONFIRMED_STREET_NOT_IDENTIFIED,
    NOT_CONFIRMED,
    NOT_PROVIDED;

    public String value() {
        return name();
    }

    public static LocationIdentificationType fromValue(String v) {
        return valueOf(v);
    }

}
