//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demo.schemas.crip package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IdentifyAddressRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "identifyAddressRequest");
    private final static QName _IdentifyAddressResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "identifyAddressResponse");
    private final static QName _AddressInvestigationRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "addressInvestigationRequest");
    private final static QName _AddressInvestigationResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "addressInvestigationResponse");
    private final static QName _GetReportRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getReportRequest");
    private final static QName _GetReportResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getReportResponse");
    private final static QName _GetArchivedReportRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getArchivedReportRequest");
    private final static QName _GetArchivedReportResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getArchivedReportResponse");
    private final static QName _GetDebtDetailsRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getDebtDetailsRequest");
    private final static QName _GetDebtDetailsResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getDebtDetailsResponse");
    private final static QName _OrderOfflineReportRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "orderOfflineReportRequest");
    private final static QName _OrderOfflineReportResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "orderOfflineReportResponse");
    private final static QName _GetListOfReadyOfflineReportsRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getListOfReadyOfflineReportsRequest");
    private final static QName _GetListOfReadyOfflineReportsResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getListOfReadyOfflineReportsResponse");
    private final static QName _PollOfflineReportResponseRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "pollOfflineReportResponseRequest");
    private final static QName _PollOfflineReportResponseResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "pollOfflineReportResponseResponse");
    private final static QName _IdVerificationRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "idVerificationRequest");
    private final static QName _IdVerificationResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "idVerificationResponse");
    private final static QName _SubmitDataIssueRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "submitDataIssueRequest");
    private final static QName _SubmitDataIssueResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "submitDataIssueResponse");
    private final static QName _CancelDataIssueRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "cancelDataIssueRequest");
    private final static QName _CancelDataIssueResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "cancelDataIssueResponse");
    private final static QName _GetDataIssueStatusRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getDataIssueStatusRequest");
    private final static QName _GetDataIssueStatusResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getDataIssueStatusResponse");
    private final static QName _CreateJobESchKgRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "createJobESchKgRequest");
    private final static QName _CreateJobESchKgResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "createJobESchKgResponse");
    private final static QName _GetStatusESchKgRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getStatusESchKgRequest");
    private final static QName _GetStatusESchKgResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getStatusESchKgResponse");
    private final static QName _GetLastDocumentESchKgRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getLastDocumentESchKgRequest");
    private final static QName _GetLastDocumentESchKgResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getLastDocumentESchKgResponse");
    private final static QName _GetWebAccessTokenESchKgRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getWebAccessTokenESchKgRequest");
    private final static QName _GetWebAccessTokenESchKgResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "getWebAccessTokenESchKgResponse");
    private final static QName _CheckOfflineReportOfficeRequest_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "checkOfflineReportOfficeRequest");
    private final static QName _CheckOfflineReportOfficeResponse_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "checkOfflineReportOfficeResponse");
    private final static QName _Error_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "error");
    private final static QName _ESchKgClaimInterestRate_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "interestRate");
    private final static QName _ESchKgClaimType_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "type");
    private final static QName _TypeGetWebAccessTokenESchKgResponseWebAccessToken_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "webAccessToken");
    private final static QName _TypeGetWebAccessTokenESchKgRequestValidUntil_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "validUntil");
    private final static QName _TypeGetLastDocumentESchKgResponseDocument_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "document");
    private final static QName _TypeGetLastDocumentESchKgRequestExternalId_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "externalId");
    private final static QName _TypeGetLastDocumentESchKgRequestOrderId_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "orderId");
    private final static QName _TypeCreateJobESchKgRequestCaseGroup_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "caseGroup");
    private final static QName _TypeCreateJobESchKgRequestCaseGroupType_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "caseGroupType");
    private final static QName _TypeCreateJobESchKgRequestRepresentative_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "representative");
    private final static QName _TypeCreateJobESchKgRequestEnforcementStatus_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "enforcementStatus");
    private final static QName _TypeCreateJobESchKgRequestLegalFormTypeOriginal_QNAME = new QName("http://www.crif-online.ch/webservices/crifsoapservice/v1.00", "legalFormTypeOriginal");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demo.schemas.crip
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TypeIdentifyAddressRequest }
     * 
     */
    public TypeIdentifyAddressRequest createTypeIdentifyAddressRequest() {
        return new TypeIdentifyAddressRequest();
    }

    /**
     * Create an instance of {@link TypeIdentifyAddressResponse }
     * 
     */
    public TypeIdentifyAddressResponse createTypeIdentifyAddressResponse() {
        return new TypeIdentifyAddressResponse();
    }

    /**
     * Create an instance of {@link TypeAddressInvestigationRequest }
     * 
     */
    public TypeAddressInvestigationRequest createTypeAddressInvestigationRequest() {
        return new TypeAddressInvestigationRequest();
    }

    /**
     * Create an instance of {@link TypeAddressInvestigationResponse }
     * 
     */
    public TypeAddressInvestigationResponse createTypeAddressInvestigationResponse() {
        return new TypeAddressInvestigationResponse();
    }

    /**
     * Create an instance of {@link TypeGetReportRequest }
     * 
     */
    public TypeGetReportRequest createTypeGetReportRequest() {
        return new TypeGetReportRequest();
    }

    /**
     * Create an instance of {@link TypeGetReportResponse }
     * 
     */
    public TypeGetReportResponse createTypeGetReportResponse() {
        return new TypeGetReportResponse();
    }

    /**
     * Create an instance of {@link TypeGetArchivedReportRequest }
     * 
     */
    public TypeGetArchivedReportRequest createTypeGetArchivedReportRequest() {
        return new TypeGetArchivedReportRequest();
    }

    /**
     * Create an instance of {@link TypeGetArchivedReportResponse }
     * 
     */
    public TypeGetArchivedReportResponse createTypeGetArchivedReportResponse() {
        return new TypeGetArchivedReportResponse();
    }

    /**
     * Create an instance of {@link TypeGetDebtDetailsRequest }
     * 
     */
    public TypeGetDebtDetailsRequest createTypeGetDebtDetailsRequest() {
        return new TypeGetDebtDetailsRequest();
    }

    /**
     * Create an instance of {@link TypeGetDebtDetailsResponse }
     * 
     */
    public TypeGetDebtDetailsResponse createTypeGetDebtDetailsResponse() {
        return new TypeGetDebtDetailsResponse();
    }

    /**
     * Create an instance of {@link TypeOrderOfflineReportRequest }
     * 
     */
    public TypeOrderOfflineReportRequest createTypeOrderOfflineReportRequest() {
        return new TypeOrderOfflineReportRequest();
    }

    /**
     * Create an instance of {@link TypeOrderOfflineReportResponse }
     * 
     */
    public TypeOrderOfflineReportResponse createTypeOrderOfflineReportResponse() {
        return new TypeOrderOfflineReportResponse();
    }

    /**
     * Create an instance of {@link TypeGetListOfReadyOfflineReportsRequest }
     * 
     */
    public TypeGetListOfReadyOfflineReportsRequest createTypeGetListOfReadyOfflineReportsRequest() {
        return new TypeGetListOfReadyOfflineReportsRequest();
    }

    /**
     * Create an instance of {@link TypeGetListOfReadyOfflineReportsResponse }
     * 
     */
    public TypeGetListOfReadyOfflineReportsResponse createTypeGetListOfReadyOfflineReportsResponse() {
        return new TypeGetListOfReadyOfflineReportsResponse();
    }

    /**
     * Create an instance of {@link TypePollOfflineReportResponseRequest }
     * 
     */
    public TypePollOfflineReportResponseRequest createTypePollOfflineReportResponseRequest() {
        return new TypePollOfflineReportResponseRequest();
    }

    /**
     * Create an instance of {@link TypePollOfflineReportResponseResponse }
     * 
     */
    public TypePollOfflineReportResponseResponse createTypePollOfflineReportResponseResponse() {
        return new TypePollOfflineReportResponseResponse();
    }

    /**
     * Create an instance of {@link TypeIdVerificationRequest }
     * 
     */
    public TypeIdVerificationRequest createTypeIdVerificationRequest() {
        return new TypeIdVerificationRequest();
    }

    /**
     * Create an instance of {@link TypeIdVerificationResponse }
     * 
     */
    public TypeIdVerificationResponse createTypeIdVerificationResponse() {
        return new TypeIdVerificationResponse();
    }

    /**
     * Create an instance of {@link TypeSubmitDataIssueRequest }
     * 
     */
    public TypeSubmitDataIssueRequest createTypeSubmitDataIssueRequest() {
        return new TypeSubmitDataIssueRequest();
    }

    /**
     * Create an instance of {@link TypeSubmitDataIssueResponse }
     * 
     */
    public TypeSubmitDataIssueResponse createTypeSubmitDataIssueResponse() {
        return new TypeSubmitDataIssueResponse();
    }

    /**
     * Create an instance of {@link TypeCancelDataIssueRequest }
     * 
     */
    public TypeCancelDataIssueRequest createTypeCancelDataIssueRequest() {
        return new TypeCancelDataIssueRequest();
    }

    /**
     * Create an instance of {@link TypeCancelDataIssueResponse }
     * 
     */
    public TypeCancelDataIssueResponse createTypeCancelDataIssueResponse() {
        return new TypeCancelDataIssueResponse();
    }

    /**
     * Create an instance of {@link TypeGetDataIssueStatusRequest }
     * 
     */
    public TypeGetDataIssueStatusRequest createTypeGetDataIssueStatusRequest() {
        return new TypeGetDataIssueStatusRequest();
    }

    /**
     * Create an instance of {@link TypeGetDataIssueStatusResponse }
     * 
     */
    public TypeGetDataIssueStatusResponse createTypeGetDataIssueStatusResponse() {
        return new TypeGetDataIssueStatusResponse();
    }

    /**
     * Create an instance of {@link TypeCreateJobESchKgRequest }
     * 
     */
    public TypeCreateJobESchKgRequest createTypeCreateJobESchKgRequest() {
        return new TypeCreateJobESchKgRequest();
    }

    /**
     * Create an instance of {@link TypeCreateJobESchKgResponse }
     * 
     */
    public TypeCreateJobESchKgResponse createTypeCreateJobESchKgResponse() {
        return new TypeCreateJobESchKgResponse();
    }

    /**
     * Create an instance of {@link TypeGetStatusESchKgRequest }
     * 
     */
    public TypeGetStatusESchKgRequest createTypeGetStatusESchKgRequest() {
        return new TypeGetStatusESchKgRequest();
    }

    /**
     * Create an instance of {@link TypeGetStatusESchKgResponse }
     * 
     */
    public TypeGetStatusESchKgResponse createTypeGetStatusESchKgResponse() {
        return new TypeGetStatusESchKgResponse();
    }

    /**
     * Create an instance of {@link TypeGetLastDocumentESchKgRequest }
     * 
     */
    public TypeGetLastDocumentESchKgRequest createTypeGetLastDocumentESchKgRequest() {
        return new TypeGetLastDocumentESchKgRequest();
    }

    /**
     * Create an instance of {@link TypeGetLastDocumentESchKgResponse }
     * 
     */
    public TypeGetLastDocumentESchKgResponse createTypeGetLastDocumentESchKgResponse() {
        return new TypeGetLastDocumentESchKgResponse();
    }

    /**
     * Create an instance of {@link TypeGetWebAccessTokenESchKgRequest }
     * 
     */
    public TypeGetWebAccessTokenESchKgRequest createTypeGetWebAccessTokenESchKgRequest() {
        return new TypeGetWebAccessTokenESchKgRequest();
    }

    /**
     * Create an instance of {@link TypeGetWebAccessTokenESchKgResponse }
     * 
     */
    public TypeGetWebAccessTokenESchKgResponse createTypeGetWebAccessTokenESchKgResponse() {
        return new TypeGetWebAccessTokenESchKgResponse();
    }

    /**
     * Create an instance of {@link TypeCheckOfflineReportOfficeRequest }
     * 
     */
    public TypeCheckOfflineReportOfficeRequest createTypeCheckOfflineReportOfficeRequest() {
        return new TypeCheckOfflineReportOfficeRequest();
    }

    /**
     * Create an instance of {@link TypeCheckOfflineReportOfficeResponse }
     * 
     */
    public TypeCheckOfflineReportOfficeResponse createTypeCheckOfflineReportOfficeResponse() {
        return new TypeCheckOfflineReportOfficeResponse();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link TypeBaseRequest }
     * 
     */
    public TypeBaseRequest createTypeBaseRequest() {
        return new TypeBaseRequest();
    }

    /**
     * Create an instance of {@link TypeBaseResponse }
     * 
     */
    public TypeBaseResponse createTypeBaseResponse() {
        return new TypeBaseResponse();
    }

    /**
     * Create an instance of {@link Control }
     * 
     */
    public Control createControl() {
        return new Control();
    }

    /**
     * Create an instance of {@link AddressWithDeliverability }
     * 
     */
    public AddressWithDeliverability createAddressWithDeliverability() {
        return new AddressWithDeliverability();
    }

    /**
     * Create an instance of {@link IdentityDescriptor }
     * 
     */
    public IdentityDescriptor createIdentityDescriptor() {
        return new IdentityDescriptor();
    }

    /**
     * Create an instance of {@link KeyValuePair }
     * 
     */
    public KeyValuePair createKeyValuePair() {
        return new KeyValuePair();
    }

    /**
     * Create an instance of {@link PersonAddressDescription }
     * 
     */
    public PersonAddressDescription createPersonAddressDescription() {
        return new PersonAddressDescription();
    }

    /**
     * Create an instance of {@link CompanyAddressDescription }
     * 
     */
    public CompanyAddressDescription createCompanyAddressDescription() {
        return new CompanyAddressDescription();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link ContactItem }
     * 
     */
    public ContactItem createContactItem() {
        return new ContactItem();
    }

    /**
     * Create an instance of {@link AddressMatchResult }
     * 
     */
    public AddressMatchResult createAddressMatchResult() {
        return new AddressMatchResult();
    }

    /**
     * Create an instance of {@link Candidate }
     * 
     */
    public Candidate createCandidate() {
        return new Candidate();
    }

    /**
     * Create an instance of {@link MatchedAddress }
     * 
     */
    public MatchedAddress createMatchedAddress() {
        return new MatchedAddress();
    }

    /**
     * Create an instance of {@link LocationIdentification }
     * 
     */
    public LocationIdentification createLocationIdentification() {
        return new LocationIdentification();
    }

    /**
     * Create an instance of {@link DecisionMatrix }
     * 
     */
    public DecisionMatrix createDecisionMatrix() {
        return new DecisionMatrix();
    }

    /**
     * Create an instance of {@link Subdecision }
     * 
     */
    public Subdecision createSubdecision() {
        return new Subdecision();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     */
    public Rating createRating() {
        return new Rating();
    }

    /**
     * Create an instance of {@link DebtEntry }
     * 
     */
    public DebtEntry createDebtEntry() {
        return new DebtEntry();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link OfflineReportIdentifier }
     * 
     */
    public OfflineReportIdentifier createOfflineReportIdentifier() {
        return new OfflineReportIdentifier();
    }

    /**
     * Create an instance of {@link ReportDetails }
     * 
     */
    public ReportDetails createReportDetails() {
        return new ReportDetails();
    }

    /**
     * Create an instance of {@link ControlPerson }
     * 
     */
    public ControlPerson createControlPerson() {
        return new ControlPerson();
    }

    /**
     * Create an instance of {@link ComplianceCheckResult }
     * 
     */
    public ComplianceCheckResult createComplianceCheckResult() {
        return new ComplianceCheckResult();
    }

    /**
     * Create an instance of {@link ComplianceCheckedEntity }
     * 
     */
    public ComplianceCheckedEntity createComplianceCheckedEntity() {
        return new ComplianceCheckedEntity();
    }

    /**
     * Create an instance of {@link ComplianceFoundEntity }
     * 
     */
    public ComplianceFoundEntity createComplianceFoundEntity() {
        return new ComplianceFoundEntity();
    }

    /**
     * Create an instance of {@link ComplianceListDescription }
     * 
     */
    public ComplianceListDescription createComplianceListDescription() {
        return new ComplianceListDescription();
    }

    /**
     * Create an instance of {@link ComplianceMatchInformation }
     * 
     */
    public ComplianceMatchInformation createComplianceMatchInformation() {
        return new ComplianceMatchInformation();
    }

    /**
     * Create an instance of {@link ScoreAnalysis }
     * 
     */
    public ScoreAnalysis createScoreAnalysis() {
        return new ScoreAnalysis();
    }

    /**
     * Create an instance of {@link ScoreDecisionRange }
     * 
     */
    public ScoreDecisionRange createScoreDecisionRange() {
        return new ScoreDecisionRange();
    }

    /**
     * Create an instance of {@link BusinessIndustryLicense }
     * 
     */
    public BusinessIndustryLicense createBusinessIndustryLicense() {
        return new BusinessIndustryLicense();
    }

    /**
     * Create an instance of {@link IndustryCode }
     * 
     */
    public IndustryCode createIndustryCode() {
        return new IndustryCode();
    }

    /**
     * Create an instance of {@link FinancialStatement }
     * 
     */
    public FinancialStatement createFinancialStatement() {
        return new FinancialStatement();
    }

    /**
     * Create an instance of {@link FinancialStatementElement }
     * 
     */
    public FinancialStatementElement createFinancialStatementElement() {
        return new FinancialStatementElement();
    }

    /**
     * Create an instance of {@link CreditRatio }
     * 
     */
    public CreditRatio createCreditRatio() {
        return new CreditRatio();
    }

    /**
     * Create an instance of {@link BranchOfficeList }
     * 
     */
    public BranchOfficeList createBranchOfficeList() {
        return new BranchOfficeList();
    }

    /**
     * Create an instance of {@link BranchOfficeListItem }
     * 
     */
    public BranchOfficeListItem createBranchOfficeListItem() {
        return new BranchOfficeListItem();
    }

    /**
     * Create an instance of {@link PublicationList }
     * 
     */
    public PublicationList createPublicationList() {
        return new PublicationList();
    }

    /**
     * Create an instance of {@link Publication }
     * 
     */
    public Publication createPublication() {
        return new Publication();
    }

    /**
     * Create an instance of {@link FurtherRelations }
     * 
     */
    public FurtherRelations createFurtherRelations() {
        return new FurtherRelations();
    }

    /**
     * Create an instance of {@link WhoOwnsWhom }
     * 
     */
    public WhoOwnsWhom createWhoOwnsWhom() {
        return new WhoOwnsWhom();
    }

    /**
     * Create an instance of {@link WowAddress }
     * 
     */
    public WowAddress createWowAddress() {
        return new WowAddress();
    }

    /**
     * Create an instance of {@link WowRelation }
     * 
     */
    public WowRelation createWowRelation() {
        return new WowRelation();
    }

    /**
     * Create an instance of {@link OrganizationPositionList }
     * 
     */
    public OrganizationPositionList createOrganizationPositionList() {
        return new OrganizationPositionList();
    }

    /**
     * Create an instance of {@link OrganizationPosition }
     * 
     */
    public OrganizationPosition createOrganizationPosition() {
        return new OrganizationPosition();
    }

    /**
     * Create an instance of {@link OrganizationPositionFunction }
     * 
     */
    public OrganizationPositionFunction createOrganizationPositionFunction() {
        return new OrganizationPositionFunction();
    }

    /**
     * Create an instance of {@link PaymentDelay }
     * 
     */
    public PaymentDelay createPaymentDelay() {
        return new PaymentDelay();
    }

    /**
     * Create an instance of {@link CompanyBaseData }
     * 
     */
    public CompanyBaseData createCompanyBaseData() {
        return new CompanyBaseData();
    }

    /**
     * Create an instance of {@link CompanyHistoryItem }
     * 
     */
    public CompanyHistoryItem createCompanyHistoryItem() {
        return new CompanyHistoryItem();
    }

    /**
     * Create an instance of {@link CompanyHistoryItemActivityStatus }
     * 
     */
    public CompanyHistoryItemActivityStatus createCompanyHistoryItemActivityStatus() {
        return new CompanyHistoryItemActivityStatus();
    }

    /**
     * Create an instance of {@link CompanyHistoryItemAddress }
     * 
     */
    public CompanyHistoryItemAddress createCompanyHistoryItemAddress() {
        return new CompanyHistoryItemAddress();
    }

    /**
     * Create an instance of {@link CompanyHistoryItemAmount }
     * 
     */
    public CompanyHistoryItemAmount createCompanyHistoryItemAmount() {
        return new CompanyHistoryItemAmount();
    }

    /**
     * Create an instance of {@link CompanyHistoryItemLegalForm }
     * 
     */
    public CompanyHistoryItemLegalForm createCompanyHistoryItemLegalForm() {
        return new CompanyHistoryItemLegalForm();
    }

    /**
     * Create an instance of {@link CompanyHistoryItemLocation }
     * 
     */
    public CompanyHistoryItemLocation createCompanyHistoryItemLocation() {
        return new CompanyHistoryItemLocation();
    }

    /**
     * Create an instance of {@link CompanyHistoryItemText }
     * 
     */
    public CompanyHistoryItemText createCompanyHistoryItemText() {
        return new CompanyHistoryItemText();
    }

    /**
     * Create an instance of {@link CompanyRegistrationData }
     * 
     */
    public CompanyRegistrationData createCompanyRegistrationData() {
        return new CompanyRegistrationData();
    }

    /**
     * Create an instance of {@link CompanyDetailData }
     * 
     */
    public CompanyDetailData createCompanyDetailData() {
        return new CompanyDetailData();
    }

    /**
     * Create an instance of {@link Range }
     * 
     */
    public Range createRange() {
        return new Range();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link BankAccount }
     * 
     */
    public BankAccount createBankAccount() {
        return new BankAccount();
    }

    /**
     * Create an instance of {@link IdVerificationRequestData }
     * 
     */
    public IdVerificationRequestData createIdVerificationRequestData() {
        return new IdVerificationRequestData();
    }

    /**
     * Create an instance of {@link IdVerificationDocument }
     * 
     */
    public IdVerificationDocument createIdVerificationDocument() {
        return new IdVerificationDocument();
    }

    /**
     * Create an instance of {@link IdVerificationPerson }
     * 
     */
    public IdVerificationPerson createIdVerificationPerson() {
        return new IdVerificationPerson();
    }

    /**
     * Create an instance of {@link IdVerificationResponseData }
     * 
     */
    public IdVerificationResponseData createIdVerificationResponseData() {
        return new IdVerificationResponseData();
    }

    /**
     * Create an instance of {@link IdVerificationContent }
     * 
     */
    public IdVerificationContent createIdVerificationContent() {
        return new IdVerificationContent();
    }

    /**
     * Create an instance of {@link BinaryData }
     * 
     */
    public BinaryData createBinaryData() {
        return new BinaryData();
    }

    /**
     * Create an instance of {@link IdVerificationChecks }
     * 
     */
    public IdVerificationChecks createIdVerificationChecks() {
        return new IdVerificationChecks();
    }

    /**
     * Create an instance of {@link IdVerificationComparisonElement }
     * 
     */
    public IdVerificationComparisonElement createIdVerificationComparisonElement() {
        return new IdVerificationComparisonElement();
    }

    /**
     * Create an instance of {@link SchufaResponseData }
     * 
     */
    public SchufaResponseData createSchufaResponseData() {
        return new SchufaResponseData();
    }

    /**
     * Create an instance of {@link SchufaPersonData }
     * 
     */
    public SchufaPersonData createSchufaPersonData() {
        return new SchufaPersonData();
    }

    /**
     * Create an instance of {@link SchufaIdentification }
     * 
     */
    public SchufaIdentification createSchufaIdentification() {
        return new SchufaIdentification();
    }

    /**
     * Create an instance of {@link SchufaScore }
     * 
     */
    public SchufaScore createSchufaScore() {
        return new SchufaScore();
    }

    /**
     * Create an instance of {@link SchufaBaseFeature }
     * 
     */
    public SchufaBaseFeature createSchufaBaseFeature() {
        return new SchufaBaseFeature();
    }

    /**
     * Create an instance of {@link SchufaFeature }
     * 
     */
    public SchufaFeature createSchufaFeature() {
        return new SchufaFeature();
    }

    /**
     * Create an instance of {@link SchufaTextFeature }
     * 
     */
    public SchufaTextFeature createSchufaTextFeature() {
        return new SchufaTextFeature();
    }

    /**
     * Create an instance of {@link ESchKgJobData }
     * 
     */
    public ESchKgJobData createESchKgJobData() {
        return new ESchKgJobData();
    }

    /**
     * Create an instance of {@link ESchKgOrderData }
     * 
     */
    public ESchKgOrderData createESchKgOrderData() {
        return new ESchKgOrderData();
    }

    /**
     * Create an instance of {@link ESchKgJobDescription }
     * 
     */
    public ESchKgJobDescription createESchKgJobDescription() {
        return new ESchKgJobDescription();
    }

    /**
     * Create an instance of {@link PaymentList }
     * 
     */
    public PaymentList createPaymentList() {
        return new PaymentList();
    }

    /**
     * Create an instance of {@link JobList }
     * 
     */
    public JobList createJobList() {
        return new JobList();
    }

    /**
     * Create an instance of {@link ClaimList }
     * 
     */
    public ClaimList createClaimList() {
        return new ClaimList();
    }

    /**
     * Create an instance of {@link ESchKgClaim }
     * 
     */
    public ESchKgClaim createESchKgClaim() {
        return new ESchKgClaim();
    }

    /**
     * Create an instance of {@link ESchKgPaymentData }
     * 
     */
    public ESchKgPaymentData createESchKgPaymentData() {
        return new ESchKgPaymentData();
    }

    /**
     * Create an instance of {@link ESchKgReimbursementData }
     * 
     */
    public ESchKgReimbursementData createESchKgReimbursementData() {
        return new ESchKgReimbursementData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeIdentifyAddressRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeIdentifyAddressRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "identifyAddressRequest")
    public JAXBElement<TypeIdentifyAddressRequest> createIdentifyAddressRequest(TypeIdentifyAddressRequest value) {
        return new JAXBElement<TypeIdentifyAddressRequest>(_IdentifyAddressRequest_QNAME, TypeIdentifyAddressRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeIdentifyAddressResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeIdentifyAddressResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "identifyAddressResponse")
    public JAXBElement<TypeIdentifyAddressResponse> createIdentifyAddressResponse(TypeIdentifyAddressResponse value) {
        return new JAXBElement<TypeIdentifyAddressResponse>(_IdentifyAddressResponse_QNAME, TypeIdentifyAddressResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAddressInvestigationRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeAddressInvestigationRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "addressInvestigationRequest")
    public JAXBElement<TypeAddressInvestigationRequest> createAddressInvestigationRequest(TypeAddressInvestigationRequest value) {
        return new JAXBElement<TypeAddressInvestigationRequest>(_AddressInvestigationRequest_QNAME, TypeAddressInvestigationRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeAddressInvestigationResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeAddressInvestigationResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "addressInvestigationResponse")
    public JAXBElement<TypeAddressInvestigationResponse> createAddressInvestigationResponse(TypeAddressInvestigationResponse value) {
        return new JAXBElement<TypeAddressInvestigationResponse>(_AddressInvestigationResponse_QNAME, TypeAddressInvestigationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetReportRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetReportRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getReportRequest")
    public JAXBElement<TypeGetReportRequest> createGetReportRequest(TypeGetReportRequest value) {
        return new JAXBElement<TypeGetReportRequest>(_GetReportRequest_QNAME, TypeGetReportRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetReportResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetReportResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getReportResponse")
    public JAXBElement<TypeGetReportResponse> createGetReportResponse(TypeGetReportResponse value) {
        return new JAXBElement<TypeGetReportResponse>(_GetReportResponse_QNAME, TypeGetReportResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetArchivedReportRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetArchivedReportRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getArchivedReportRequest")
    public JAXBElement<TypeGetArchivedReportRequest> createGetArchivedReportRequest(TypeGetArchivedReportRequest value) {
        return new JAXBElement<TypeGetArchivedReportRequest>(_GetArchivedReportRequest_QNAME, TypeGetArchivedReportRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetArchivedReportResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetArchivedReportResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getArchivedReportResponse")
    public JAXBElement<TypeGetArchivedReportResponse> createGetArchivedReportResponse(TypeGetArchivedReportResponse value) {
        return new JAXBElement<TypeGetArchivedReportResponse>(_GetArchivedReportResponse_QNAME, TypeGetArchivedReportResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetDebtDetailsRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetDebtDetailsRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getDebtDetailsRequest")
    public JAXBElement<TypeGetDebtDetailsRequest> createGetDebtDetailsRequest(TypeGetDebtDetailsRequest value) {
        return new JAXBElement<TypeGetDebtDetailsRequest>(_GetDebtDetailsRequest_QNAME, TypeGetDebtDetailsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetDebtDetailsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetDebtDetailsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getDebtDetailsResponse")
    public JAXBElement<TypeGetDebtDetailsResponse> createGetDebtDetailsResponse(TypeGetDebtDetailsResponse value) {
        return new JAXBElement<TypeGetDebtDetailsResponse>(_GetDebtDetailsResponse_QNAME, TypeGetDebtDetailsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeOrderOfflineReportRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeOrderOfflineReportRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "orderOfflineReportRequest")
    public JAXBElement<TypeOrderOfflineReportRequest> createOrderOfflineReportRequest(TypeOrderOfflineReportRequest value) {
        return new JAXBElement<TypeOrderOfflineReportRequest>(_OrderOfflineReportRequest_QNAME, TypeOrderOfflineReportRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeOrderOfflineReportResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeOrderOfflineReportResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "orderOfflineReportResponse")
    public JAXBElement<TypeOrderOfflineReportResponse> createOrderOfflineReportResponse(TypeOrderOfflineReportResponse value) {
        return new JAXBElement<TypeOrderOfflineReportResponse>(_OrderOfflineReportResponse_QNAME, TypeOrderOfflineReportResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetListOfReadyOfflineReportsRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetListOfReadyOfflineReportsRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getListOfReadyOfflineReportsRequest")
    public JAXBElement<TypeGetListOfReadyOfflineReportsRequest> createGetListOfReadyOfflineReportsRequest(TypeGetListOfReadyOfflineReportsRequest value) {
        return new JAXBElement<TypeGetListOfReadyOfflineReportsRequest>(_GetListOfReadyOfflineReportsRequest_QNAME, TypeGetListOfReadyOfflineReportsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetListOfReadyOfflineReportsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetListOfReadyOfflineReportsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getListOfReadyOfflineReportsResponse")
    public JAXBElement<TypeGetListOfReadyOfflineReportsResponse> createGetListOfReadyOfflineReportsResponse(TypeGetListOfReadyOfflineReportsResponse value) {
        return new JAXBElement<TypeGetListOfReadyOfflineReportsResponse>(_GetListOfReadyOfflineReportsResponse_QNAME, TypeGetListOfReadyOfflineReportsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePollOfflineReportResponseRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypePollOfflineReportResponseRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "pollOfflineReportResponseRequest")
    public JAXBElement<TypePollOfflineReportResponseRequest> createPollOfflineReportResponseRequest(TypePollOfflineReportResponseRequest value) {
        return new JAXBElement<TypePollOfflineReportResponseRequest>(_PollOfflineReportResponseRequest_QNAME, TypePollOfflineReportResponseRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypePollOfflineReportResponseResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypePollOfflineReportResponseResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "pollOfflineReportResponseResponse")
    public JAXBElement<TypePollOfflineReportResponseResponse> createPollOfflineReportResponseResponse(TypePollOfflineReportResponseResponse value) {
        return new JAXBElement<TypePollOfflineReportResponseResponse>(_PollOfflineReportResponseResponse_QNAME, TypePollOfflineReportResponseResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeIdVerificationRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeIdVerificationRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "idVerificationRequest")
    public JAXBElement<TypeIdVerificationRequest> createIdVerificationRequest(TypeIdVerificationRequest value) {
        return new JAXBElement<TypeIdVerificationRequest>(_IdVerificationRequest_QNAME, TypeIdVerificationRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeIdVerificationResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeIdVerificationResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "idVerificationResponse")
    public JAXBElement<TypeIdVerificationResponse> createIdVerificationResponse(TypeIdVerificationResponse value) {
        return new JAXBElement<TypeIdVerificationResponse>(_IdVerificationResponse_QNAME, TypeIdVerificationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeSubmitDataIssueRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeSubmitDataIssueRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "submitDataIssueRequest")
    public JAXBElement<TypeSubmitDataIssueRequest> createSubmitDataIssueRequest(TypeSubmitDataIssueRequest value) {
        return new JAXBElement<TypeSubmitDataIssueRequest>(_SubmitDataIssueRequest_QNAME, TypeSubmitDataIssueRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeSubmitDataIssueResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeSubmitDataIssueResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "submitDataIssueResponse")
    public JAXBElement<TypeSubmitDataIssueResponse> createSubmitDataIssueResponse(TypeSubmitDataIssueResponse value) {
        return new JAXBElement<TypeSubmitDataIssueResponse>(_SubmitDataIssueResponse_QNAME, TypeSubmitDataIssueResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCancelDataIssueRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeCancelDataIssueRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "cancelDataIssueRequest")
    public JAXBElement<TypeCancelDataIssueRequest> createCancelDataIssueRequest(TypeCancelDataIssueRequest value) {
        return new JAXBElement<TypeCancelDataIssueRequest>(_CancelDataIssueRequest_QNAME, TypeCancelDataIssueRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCancelDataIssueResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeCancelDataIssueResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "cancelDataIssueResponse")
    public JAXBElement<TypeCancelDataIssueResponse> createCancelDataIssueResponse(TypeCancelDataIssueResponse value) {
        return new JAXBElement<TypeCancelDataIssueResponse>(_CancelDataIssueResponse_QNAME, TypeCancelDataIssueResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetDataIssueStatusRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetDataIssueStatusRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getDataIssueStatusRequest")
    public JAXBElement<TypeGetDataIssueStatusRequest> createGetDataIssueStatusRequest(TypeGetDataIssueStatusRequest value) {
        return new JAXBElement<TypeGetDataIssueStatusRequest>(_GetDataIssueStatusRequest_QNAME, TypeGetDataIssueStatusRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetDataIssueStatusResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetDataIssueStatusResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getDataIssueStatusResponse")
    public JAXBElement<TypeGetDataIssueStatusResponse> createGetDataIssueStatusResponse(TypeGetDataIssueStatusResponse value) {
        return new JAXBElement<TypeGetDataIssueStatusResponse>(_GetDataIssueStatusResponse_QNAME, TypeGetDataIssueStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCreateJobESchKgRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeCreateJobESchKgRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "createJobESchKgRequest")
    public JAXBElement<TypeCreateJobESchKgRequest> createCreateJobESchKgRequest(TypeCreateJobESchKgRequest value) {
        return new JAXBElement<TypeCreateJobESchKgRequest>(_CreateJobESchKgRequest_QNAME, TypeCreateJobESchKgRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCreateJobESchKgResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeCreateJobESchKgResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "createJobESchKgResponse")
    public JAXBElement<TypeCreateJobESchKgResponse> createCreateJobESchKgResponse(TypeCreateJobESchKgResponse value) {
        return new JAXBElement<TypeCreateJobESchKgResponse>(_CreateJobESchKgResponse_QNAME, TypeCreateJobESchKgResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetStatusESchKgRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetStatusESchKgRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getStatusESchKgRequest")
    public JAXBElement<TypeGetStatusESchKgRequest> createGetStatusESchKgRequest(TypeGetStatusESchKgRequest value) {
        return new JAXBElement<TypeGetStatusESchKgRequest>(_GetStatusESchKgRequest_QNAME, TypeGetStatusESchKgRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetStatusESchKgResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetStatusESchKgResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getStatusESchKgResponse")
    public JAXBElement<TypeGetStatusESchKgResponse> createGetStatusESchKgResponse(TypeGetStatusESchKgResponse value) {
        return new JAXBElement<TypeGetStatusESchKgResponse>(_GetStatusESchKgResponse_QNAME, TypeGetStatusESchKgResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetLastDocumentESchKgRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetLastDocumentESchKgRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getLastDocumentESchKgRequest")
    public JAXBElement<TypeGetLastDocumentESchKgRequest> createGetLastDocumentESchKgRequest(TypeGetLastDocumentESchKgRequest value) {
        return new JAXBElement<TypeGetLastDocumentESchKgRequest>(_GetLastDocumentESchKgRequest_QNAME, TypeGetLastDocumentESchKgRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetLastDocumentESchKgResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetLastDocumentESchKgResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getLastDocumentESchKgResponse")
    public JAXBElement<TypeGetLastDocumentESchKgResponse> createGetLastDocumentESchKgResponse(TypeGetLastDocumentESchKgResponse value) {
        return new JAXBElement<TypeGetLastDocumentESchKgResponse>(_GetLastDocumentESchKgResponse_QNAME, TypeGetLastDocumentESchKgResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetWebAccessTokenESchKgRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetWebAccessTokenESchKgRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getWebAccessTokenESchKgRequest")
    public JAXBElement<TypeGetWebAccessTokenESchKgRequest> createGetWebAccessTokenESchKgRequest(TypeGetWebAccessTokenESchKgRequest value) {
        return new JAXBElement<TypeGetWebAccessTokenESchKgRequest>(_GetWebAccessTokenESchKgRequest_QNAME, TypeGetWebAccessTokenESchKgRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeGetWebAccessTokenESchKgResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeGetWebAccessTokenESchKgResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "getWebAccessTokenESchKgResponse")
    public JAXBElement<TypeGetWebAccessTokenESchKgResponse> createGetWebAccessTokenESchKgResponse(TypeGetWebAccessTokenESchKgResponse value) {
        return new JAXBElement<TypeGetWebAccessTokenESchKgResponse>(_GetWebAccessTokenESchKgResponse_QNAME, TypeGetWebAccessTokenESchKgResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCheckOfflineReportOfficeRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeCheckOfflineReportOfficeRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "checkOfflineReportOfficeRequest")
    public JAXBElement<TypeCheckOfflineReportOfficeRequest> createCheckOfflineReportOfficeRequest(TypeCheckOfflineReportOfficeRequest value) {
        return new JAXBElement<TypeCheckOfflineReportOfficeRequest>(_CheckOfflineReportOfficeRequest_QNAME, TypeCheckOfflineReportOfficeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeCheckOfflineReportOfficeResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeCheckOfflineReportOfficeResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "checkOfflineReportOfficeResponse")
    public JAXBElement<TypeCheckOfflineReportOfficeResponse> createCheckOfflineReportOfficeResponse(TypeCheckOfflineReportOfficeResponse value) {
        return new JAXBElement<TypeCheckOfflineReportOfficeResponse>(_CheckOfflineReportOfficeResponse_QNAME, TypeCheckOfflineReportOfficeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Error }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Error }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "error")
    public JAXBElement<Error> createError(Error value) {
        return new JAXBElement<Error>(_Error_QNAME, Error.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "interestRate", scope = ESchKgClaim.class)
    public JAXBElement<Double> createESchKgClaimInterestRate(Double value) {
        return new JAXBElement<Double>(_ESchKgClaimInterestRate_QNAME, Double.class, ESchKgClaim.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClaimType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ClaimType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "type", scope = ESchKgClaim.class)
    public JAXBElement<ClaimType> createESchKgClaimType(ClaimType value) {
        return new JAXBElement<ClaimType>(_ESchKgClaimType_QNAME, ClaimType.class, ESchKgClaim.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "webAccessToken", scope = TypeGetWebAccessTokenESchKgResponse.class)
    public JAXBElement<String> createTypeGetWebAccessTokenESchKgResponseWebAccessToken(String value) {
        return new JAXBElement<String>(_TypeGetWebAccessTokenESchKgResponseWebAccessToken_QNAME, String.class, TypeGetWebAccessTokenESchKgResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "validUntil", scope = TypeGetWebAccessTokenESchKgRequest.class)
    public JAXBElement<String> createTypeGetWebAccessTokenESchKgRequestValidUntil(String value) {
        return new JAXBElement<String>(_TypeGetWebAccessTokenESchKgRequestValidUntil_QNAME, String.class, TypeGetWebAccessTokenESchKgRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "document", scope = TypeGetLastDocumentESchKgResponse.class)
    public JAXBElement<String> createTypeGetLastDocumentESchKgResponseDocument(String value) {
        return new JAXBElement<String>(_TypeGetLastDocumentESchKgResponseDocument_QNAME, String.class, TypeGetLastDocumentESchKgResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "externalId", scope = TypeGetLastDocumentESchKgRequest.class)
    public JAXBElement<String> createTypeGetLastDocumentESchKgRequestExternalId(String value) {
        return new JAXBElement<String>(_TypeGetLastDocumentESchKgRequestExternalId_QNAME, String.class, TypeGetLastDocumentESchKgRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "orderId", scope = TypeGetLastDocumentESchKgRequest.class)
    public JAXBElement<String> createTypeGetLastDocumentESchKgRequestOrderId(String value) {
        return new JAXBElement<String>(_TypeGetLastDocumentESchKgRequestOrderId_QNAME, String.class, TypeGetLastDocumentESchKgRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "externalId", scope = TypeGetStatusESchKgRequest.class)
    public JAXBElement<String> createTypeGetStatusESchKgRequestExternalId(String value) {
        return new JAXBElement<String>(_TypeGetLastDocumentESchKgRequestExternalId_QNAME, String.class, TypeGetStatusESchKgRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "orderId", scope = TypeGetStatusESchKgRequest.class)
    public JAXBElement<String> createTypeGetStatusESchKgRequestOrderId(String value) {
        return new JAXBElement<String>(_TypeGetLastDocumentESchKgRequestOrderId_QNAME, String.class, TypeGetStatusESchKgRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "externalId", scope = TypeCreateJobESchKgRequest.class)
    public JAXBElement<String> createTypeCreateJobESchKgRequestExternalId(String value) {
        return new JAXBElement<String>(_TypeGetLastDocumentESchKgRequestExternalId_QNAME, String.class, TypeCreateJobESchKgRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "caseGroup", scope = TypeCreateJobESchKgRequest.class)
    public JAXBElement<String> createTypeCreateJobESchKgRequestCaseGroup(String value) {
        return new JAXBElement<String>(_TypeCreateJobESchKgRequestCaseGroup_QNAME, String.class, TypeCreateJobESchKgRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "caseGroupType", scope = TypeCreateJobESchKgRequest.class)
    public JAXBElement<String> createTypeCreateJobESchKgRequestCaseGroupType(String value) {
        return new JAXBElement<String>(_TypeCreateJobESchKgRequestCaseGroupType_QNAME, String.class, TypeCreateJobESchKgRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "representative", scope = TypeCreateJobESchKgRequest.class)
    public JAXBElement<String> createTypeCreateJobESchKgRequestRepresentative(String value) {
        return new JAXBElement<String>(_TypeCreateJobESchKgRequestRepresentative_QNAME, String.class, TypeCreateJobESchKgRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnforcementStatus }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EnforcementStatus }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "enforcementStatus", scope = TypeCreateJobESchKgRequest.class)
    public JAXBElement<EnforcementStatus> createTypeCreateJobESchKgRequestEnforcementStatus(EnforcementStatus value) {
        return new JAXBElement<EnforcementStatus>(_TypeCreateJobESchKgRequestEnforcementStatus_QNAME, EnforcementStatus.class, TypeCreateJobESchKgRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", name = "legalFormTypeOriginal", scope = TypeCreateJobESchKgRequest.class)
    public JAXBElement<String> createTypeCreateJobESchKgRequestLegalFormTypeOriginal(String value) {
        return new JAXBElement<String>(_TypeCreateJobESchKgRequestLegalFormTypeOriginal_QNAME, String.class, TypeCreateJobESchKgRequest.class, value);
    }

}
