//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OfflineReportType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OfflineReportType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BA"/&gt;
 *     &lt;enumeration value="BA_EXPRESS"/&gt;
 *     &lt;enumeration value="EWK"/&gt;
 *     &lt;enumeration value="EWK_EXPRESS"/&gt;
 *     &lt;enumeration value="LGE"/&gt;
 *     &lt;enumeration value="LGE_EXPRESS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OfflineReportType")
@XmlEnum
public enum OfflineReportType {

    BA,
    BA_EXPRESS,
    EWK,
    EWK_EXPRESS,
    LGE,
    LGE_EXPRESS;

    public String value() {
        return name();
    }

    public static OfflineReportType fromValue(String v) {
        return valueOf(v);
    }

}
