//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OfflineReportRejectionReason.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OfflineReportRejectionReason"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ADDRESS_IS_BUSINESS_ADDRESS"/&gt;
 *     &lt;enumeration value="ADDRESS_IS_SECONDARY_ADDRES"/&gt;
 *     &lt;enumeration value="CROSS_BORDER_COMMUTER"/&gt;
 *     &lt;enumeration value="DATA_PRIVACY_PROTECTION"/&gt;
 *     &lt;enumeration value="DISCLOSURE_REJECTED"/&gt;
 *     &lt;enumeration value="LEGAENTY_ADDRESS_UNKNOWN"/&gt;
 *     &lt;enumeration value="LEGAENTY_DECEASED"/&gt;
 *     &lt;enumeration value="LEGAENTY_UNKNOWN"/&gt;
 *     &lt;enumeration value="OFFICE_REQUIRES_EXACT_BIRTHDATE"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *     &lt;enumeration value="PROOF_OF_BUSINESS_RELATIONSHIP_MISSING"/&gt;
 *     &lt;enumeration value="PROOF_OF_INTEREST_MISSING"/&gt;
 *     &lt;enumeration value="PROOF_OF_INTEREST_UNSIGNED"/&gt;
 *     &lt;enumeration value="REGISTRATION_PENDING"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OfflineReportRejectionReason")
@XmlEnum
public enum OfflineReportRejectionReason {

    ADDRESS_IS_BUSINESS_ADDRESS,
    ADDRESS_IS_SECONDARY_ADDRES,
    CROSS_BORDER_COMMUTER,
    DATA_PRIVACY_PROTECTION,
    DISCLOSURE_REJECTED,
    LEGAENTY_ADDRESS_UNKNOWN,
    LEGAENTY_DECEASED,
    LEGAENTY_UNKNOWN,
    OFFICE_REQUIRES_EXACT_BIRTHDATE,
    OTHER,
    PROOF_OF_BUSINESS_RELATIONSHIP_MISSING,
    PROOF_OF_INTEREST_MISSING,
    PROOF_OF_INTEREST_UNSIGNED,
    REGISTRATION_PENDING;

    public String value() {
        return name();
    }

    public static OfflineReportRejectionReason fromValue(String v) {
        return valueOf(v);
    }

}
