//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * OrganizationPosition element
 * 
 * <p>Java class for OrganizationPosition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrganizationPosition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nationality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="homeTown" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="highestFunction" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}OrganizationPositionFunction"/&gt;
 *         &lt;element name="furtherFunctions" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}OrganizationPositionFunction" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="share" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="signatureType" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}SignatureType" minOccurs="0"/&gt;
 *         &lt;element name="signatureOriginal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="period" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Period"/&gt;
 *         &lt;element name="addressId" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Identifier" minOccurs="0"/&gt;
 *         &lt;element name="hasDebts" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}HasDebts" minOccurs="0"/&gt;
 *         &lt;element name="nrOfPositions" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="nrOfPositionsBankrupt" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="birthDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="organizationPositions" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}OrganizationPosition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganizationPosition", propOrder = {
    "firstName",
    "name",
    "nationality",
    "homeTown",
    "city",
    "highestFunction",
    "furtherFunctions",
    "share",
    "signatureType",
    "signatureOriginal",
    "period",
    "addressId",
    "hasDebts",
    "nrOfPositions",
    "nrOfPositionsBankrupt",
    "birthDate",
    "organizationPositions"
})
public class OrganizationPosition {

    protected String firstName;
    @XmlElement(required = true)
    protected String name;
    protected String nationality;
    protected String homeTown;
    protected String city;
    @XmlElement(required = true)
    protected OrganizationPositionFunction highestFunction;
    protected List<OrganizationPositionFunction> furtherFunctions;
    protected BigDecimal share;
    @XmlSchemaType(name = "string")
    protected SignatureType signatureType;
    protected String signatureOriginal;
    @XmlElement(required = true)
    protected Period period;
    protected Identifier addressId;
    @XmlSchemaType(name = "string")
    protected HasDebts hasDebts;
    protected BigInteger nrOfPositions;
    protected BigInteger nrOfPositionsBankrupt;
    protected String birthDate;
    protected List<OrganizationPosition> organizationPositions;

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the homeTown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeTown() {
        return homeTown;
    }

    /**
     * Sets the value of the homeTown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeTown(String value) {
        this.homeTown = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the highestFunction property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationPositionFunction }
     *     
     */
    public OrganizationPositionFunction getHighestFunction() {
        return highestFunction;
    }

    /**
     * Sets the value of the highestFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationPositionFunction }
     *     
     */
    public void setHighestFunction(OrganizationPositionFunction value) {
        this.highestFunction = value;
    }

    /**
     * Gets the value of the furtherFunctions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the furtherFunctions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFurtherFunctions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganizationPositionFunction }
     * 
     * 
     */
    public List<OrganizationPositionFunction> getFurtherFunctions() {
        if (furtherFunctions == null) {
            furtherFunctions = new ArrayList<OrganizationPositionFunction>();
        }
        return this.furtherFunctions;
    }

    /**
     * Gets the value of the share property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getShare() {
        return share;
    }

    /**
     * Sets the value of the share property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setShare(BigDecimal value) {
        this.share = value;
    }

    /**
     * Gets the value of the signatureType property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignatureType() {
        return signatureType;
    }

    /**
     * Sets the value of the signatureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignatureType(SignatureType value) {
        this.signatureType = value;
    }

    /**
     * Gets the value of the signatureOriginal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureOriginal() {
        return signatureOriginal;
    }

    /**
     * Sets the value of the signatureOriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureOriginal(String value) {
        this.signatureOriginal = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setPeriod(Period value) {
        this.period = value;
    }

    /**
     * Gets the value of the addressId property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getAddressId() {
        return addressId;
    }

    /**
     * Sets the value of the addressId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setAddressId(Identifier value) {
        this.addressId = value;
    }

    /**
     * Gets the value of the hasDebts property.
     * 
     * @return
     *     possible object is
     *     {@link HasDebts }
     *     
     */
    public HasDebts getHasDebts() {
        return hasDebts;
    }

    /**
     * Sets the value of the hasDebts property.
     * 
     * @param value
     *     allowed object is
     *     {@link HasDebts }
     *     
     */
    public void setHasDebts(HasDebts value) {
        this.hasDebts = value;
    }

    /**
     * Gets the value of the nrOfPositions property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNrOfPositions() {
        return nrOfPositions;
    }

    /**
     * Sets the value of the nrOfPositions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNrOfPositions(BigInteger value) {
        this.nrOfPositions = value;
    }

    /**
     * Gets the value of the nrOfPositionsBankrupt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNrOfPositionsBankrupt() {
        return nrOfPositionsBankrupt;
    }

    /**
     * Sets the value of the nrOfPositionsBankrupt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNrOfPositionsBankrupt(BigInteger value) {
        this.nrOfPositionsBankrupt = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(String value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the organizationPositions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationPositions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganizationPositions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganizationPosition }
     * 
     * 
     */
    public List<OrganizationPosition> getOrganizationPositions() {
        if (organizationPositions == null) {
            organizationPositions = new ArrayList<OrganizationPosition>();
        }
        return this.organizationPositions;
    }

}
