//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.crif-online.ch/webservices/crifsoapservice/v1.00", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.demo.schemas.crip;
