//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * PaymentDelay structure
 * 
 * <p>Java class for PaymentDelay complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentDelay"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="inTimeRatio" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="avgDelayShortTerm" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="avgDelayLongTerm" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="paymentExpectedType" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}PaymentExpectedType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentDelay", propOrder = {
    "inTimeRatio",
    "avgDelayShortTerm",
    "avgDelayLongTerm",
    "paymentType",
    "paymentExpectedType"
})
public class PaymentDelay {

    protected BigDecimal inTimeRatio;
    protected BigInteger avgDelayShortTerm;
    protected BigInteger avgDelayLongTerm;
    protected String paymentType;
    @XmlSchemaType(name = "string")
    protected PaymentExpectedType paymentExpectedType;

    /**
     * Gets the value of the inTimeRatio property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInTimeRatio() {
        return inTimeRatio;
    }

    /**
     * Sets the value of the inTimeRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInTimeRatio(BigDecimal value) {
        this.inTimeRatio = value;
    }

    /**
     * Gets the value of the avgDelayShortTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAvgDelayShortTerm() {
        return avgDelayShortTerm;
    }

    /**
     * Sets the value of the avgDelayShortTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAvgDelayShortTerm(BigInteger value) {
        this.avgDelayShortTerm = value;
    }

    /**
     * Gets the value of the avgDelayLongTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAvgDelayLongTerm() {
        return avgDelayLongTerm;
    }

    /**
     * Sets the value of the avgDelayLongTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAvgDelayLongTerm(BigInteger value) {
        this.avgDelayLongTerm = value;
    }

    /**
     * Gets the value of the paymentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentType(String value) {
        this.paymentType = value;
    }

    /**
     * Gets the value of the paymentExpectedType property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentExpectedType }
     *     
     */
    public PaymentExpectedType getPaymentExpectedType() {
        return paymentExpectedType;
    }

    /**
     * Sets the value of the paymentExpectedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentExpectedType }
     *     
     */
    public void setPaymentExpectedType(PaymentExpectedType value) {
        this.paymentExpectedType = value;
    }

}
