//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Publication element
 * 
 * <p>Java class for Publication complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Publication"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="publicationDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="publicationCategoryOriginal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="publicationCategory" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}PublicationCategory"/&gt;
 *         &lt;element name="publicationLabels" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="publicationRegion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Publication", propOrder = {
    "publicationDate",
    "publicationCategoryOriginal",
    "publicationCategory",
    "publicationLabels",
    "language",
    "publicationRegion",
    "text"
})
public class Publication {

    @XmlElement(required = true)
    protected String publicationDate;
    protected String publicationCategoryOriginal;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PublicationCategory publicationCategory;
    protected List<String> publicationLabels;
    protected String language;
    protected String publicationRegion;
    protected String text;

    /**
     * Gets the value of the publicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationDate() {
        return publicationDate;
    }

    /**
     * Sets the value of the publicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationDate(String value) {
        this.publicationDate = value;
    }

    /**
     * Gets the value of the publicationCategoryOriginal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationCategoryOriginal() {
        return publicationCategoryOriginal;
    }

    /**
     * Sets the value of the publicationCategoryOriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationCategoryOriginal(String value) {
        this.publicationCategoryOriginal = value;
    }

    /**
     * Gets the value of the publicationCategory property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationCategory }
     *     
     */
    public PublicationCategory getPublicationCategory() {
        return publicationCategory;
    }

    /**
     * Sets the value of the publicationCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationCategory }
     *     
     */
    public void setPublicationCategory(PublicationCategory value) {
        this.publicationCategory = value;
    }

    /**
     * Gets the value of the publicationLabels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publicationLabels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublicationLabels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPublicationLabels() {
        if (publicationLabels == null) {
            publicationLabels = new ArrayList<String>();
        }
        return this.publicationLabels;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the publicationRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationRegion() {
        return publicationRegion;
    }

    /**
     * Sets the value of the publicationRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationRegion(String value) {
        this.publicationRegion = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

}
