//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Report detailed structure
 * 
 * <p>Java class for ReportDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportDetails"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="debts" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}DebtEntry" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="companyBaseData" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}CompanyBaseData" minOccurs="0"/&gt;
 *         &lt;element name="paymentDelay" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}PaymentDelay" minOccurs="0"/&gt;
 *         &lt;element name="organizationPositionList" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}OrganizationPositionList" minOccurs="0"/&gt;
 *         &lt;element name="whoOwnsWhom" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}WhoOwnsWhom" minOccurs="0"/&gt;
 *         &lt;element name="furtherRelations" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}FurtherRelations" minOccurs="0"/&gt;
 *         &lt;element name="publicationList" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}PublicationList" minOccurs="0"/&gt;
 *         &lt;element name="branchOfficeList" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}BranchOfficeList" minOccurs="0"/&gt;
 *         &lt;element name="financialStatements" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}FinancialStatement" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="financialStatementsGroup" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}FinancialStatement" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="addressHistory" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}AddressWithDeliverability" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="businessIndustryLicenses" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}BusinessIndustryLicense" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="scoreAnalysis" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}ScoreAnalysis" minOccurs="0"/&gt;
 *         &lt;element name="complianceCheckResult" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}ComplianceCheckResult" minOccurs="0"/&gt;
 *         &lt;element name="idVerificationResponseData" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}IdVerificationResponseData" minOccurs="0"/&gt;
 *         &lt;element name="schufaResponseData" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}SchufaResponseData" minOccurs="0"/&gt;
 *         &lt;element name="controlPersons" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}AddressDescription" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="controlPersonsExt" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}ControlPerson" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportDetails", propOrder = {
    "debts",
    "companyBaseData",
    "paymentDelay",
    "organizationPositionList",
    "whoOwnsWhom",
    "furtherRelations",
    "publicationList",
    "branchOfficeList",
    "financialStatements",
    "financialStatementsGroup",
    "addressHistory",
    "businessIndustryLicenses",
    "scoreAnalysis",
    "complianceCheckResult",
    "idVerificationResponseData",
    "schufaResponseData",
    "controlPersons",
    "controlPersonsExt"
})
public class ReportDetails {

    protected List<DebtEntry> debts;
    protected CompanyBaseData companyBaseData;
    protected PaymentDelay paymentDelay;
    protected OrganizationPositionList organizationPositionList;
    protected WhoOwnsWhom whoOwnsWhom;
    protected FurtherRelations furtherRelations;
    protected PublicationList publicationList;
    protected BranchOfficeList branchOfficeList;
    protected List<FinancialStatement> financialStatements;
    protected List<FinancialStatement> financialStatementsGroup;
    protected List<AddressWithDeliverability> addressHistory;
    protected List<BusinessIndustryLicense> businessIndustryLicenses;
    protected ScoreAnalysis scoreAnalysis;
    protected ComplianceCheckResult complianceCheckResult;
    protected IdVerificationResponseData idVerificationResponseData;
    protected SchufaResponseData schufaResponseData;
    protected List<AddressDescription> controlPersons;
    protected List<ControlPerson> controlPersonsExt;

    /**
     * Gets the value of the debts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the debts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDebts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DebtEntry }
     * 
     * 
     */
    public List<DebtEntry> getDebts() {
        if (debts == null) {
            debts = new ArrayList<DebtEntry>();
        }
        return this.debts;
    }

    /**
     * Gets the value of the companyBaseData property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyBaseData }
     *     
     */
    public CompanyBaseData getCompanyBaseData() {
        return companyBaseData;
    }

    /**
     * Sets the value of the companyBaseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyBaseData }
     *     
     */
    public void setCompanyBaseData(CompanyBaseData value) {
        this.companyBaseData = value;
    }

    /**
     * Gets the value of the paymentDelay property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDelay }
     *     
     */
    public PaymentDelay getPaymentDelay() {
        return paymentDelay;
    }

    /**
     * Sets the value of the paymentDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDelay }
     *     
     */
    public void setPaymentDelay(PaymentDelay value) {
        this.paymentDelay = value;
    }

    /**
     * Gets the value of the organizationPositionList property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationPositionList }
     *     
     */
    public OrganizationPositionList getOrganizationPositionList() {
        return organizationPositionList;
    }

    /**
     * Sets the value of the organizationPositionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationPositionList }
     *     
     */
    public void setOrganizationPositionList(OrganizationPositionList value) {
        this.organizationPositionList = value;
    }

    /**
     * Gets the value of the whoOwnsWhom property.
     * 
     * @return
     *     possible object is
     *     {@link WhoOwnsWhom }
     *     
     */
    public WhoOwnsWhom getWhoOwnsWhom() {
        return whoOwnsWhom;
    }

    /**
     * Sets the value of the whoOwnsWhom property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhoOwnsWhom }
     *     
     */
    public void setWhoOwnsWhom(WhoOwnsWhom value) {
        this.whoOwnsWhom = value;
    }

    /**
     * Gets the value of the furtherRelations property.
     * 
     * @return
     *     possible object is
     *     {@link FurtherRelations }
     *     
     */
    public FurtherRelations getFurtherRelations() {
        return furtherRelations;
    }

    /**
     * Sets the value of the furtherRelations property.
     * 
     * @param value
     *     allowed object is
     *     {@link FurtherRelations }
     *     
     */
    public void setFurtherRelations(FurtherRelations value) {
        this.furtherRelations = value;
    }

    /**
     * Gets the value of the publicationList property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationList }
     *     
     */
    public PublicationList getPublicationList() {
        return publicationList;
    }

    /**
     * Sets the value of the publicationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationList }
     *     
     */
    public void setPublicationList(PublicationList value) {
        this.publicationList = value;
    }

    /**
     * Gets the value of the branchOfficeList property.
     * 
     * @return
     *     possible object is
     *     {@link BranchOfficeList }
     *     
     */
    public BranchOfficeList getBranchOfficeList() {
        return branchOfficeList;
    }

    /**
     * Sets the value of the branchOfficeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BranchOfficeList }
     *     
     */
    public void setBranchOfficeList(BranchOfficeList value) {
        this.branchOfficeList = value;
    }

    /**
     * Gets the value of the financialStatements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the financialStatements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFinancialStatements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinancialStatement }
     * 
     * 
     */
    public List<FinancialStatement> getFinancialStatements() {
        if (financialStatements == null) {
            financialStatements = new ArrayList<FinancialStatement>();
        }
        return this.financialStatements;
    }

    /**
     * Gets the value of the financialStatementsGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the financialStatementsGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFinancialStatementsGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinancialStatement }
     * 
     * 
     */
    public List<FinancialStatement> getFinancialStatementsGroup() {
        if (financialStatementsGroup == null) {
            financialStatementsGroup = new ArrayList<FinancialStatement>();
        }
        return this.financialStatementsGroup;
    }

    /**
     * Gets the value of the addressHistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressHistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddressHistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressWithDeliverability }
     * 
     * 
     */
    public List<AddressWithDeliverability> getAddressHistory() {
        if (addressHistory == null) {
            addressHistory = new ArrayList<AddressWithDeliverability>();
        }
        return this.addressHistory;
    }

    /**
     * Gets the value of the businessIndustryLicenses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the businessIndustryLicenses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBusinessIndustryLicenses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BusinessIndustryLicense }
     * 
     * 
     */
    public List<BusinessIndustryLicense> getBusinessIndustryLicenses() {
        if (businessIndustryLicenses == null) {
            businessIndustryLicenses = new ArrayList<BusinessIndustryLicense>();
        }
        return this.businessIndustryLicenses;
    }

    /**
     * Gets the value of the scoreAnalysis property.
     * 
     * @return
     *     possible object is
     *     {@link ScoreAnalysis }
     *     
     */
    public ScoreAnalysis getScoreAnalysis() {
        return scoreAnalysis;
    }

    /**
     * Sets the value of the scoreAnalysis property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScoreAnalysis }
     *     
     */
    public void setScoreAnalysis(ScoreAnalysis value) {
        this.scoreAnalysis = value;
    }

    /**
     * Gets the value of the complianceCheckResult property.
     * 
     * @return
     *     possible object is
     *     {@link ComplianceCheckResult }
     *     
     */
    public ComplianceCheckResult getComplianceCheckResult() {
        return complianceCheckResult;
    }

    /**
     * Sets the value of the complianceCheckResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplianceCheckResult }
     *     
     */
    public void setComplianceCheckResult(ComplianceCheckResult value) {
        this.complianceCheckResult = value;
    }

    /**
     * Gets the value of the idVerificationResponseData property.
     * 
     * @return
     *     possible object is
     *     {@link IdVerificationResponseData }
     *     
     */
    public IdVerificationResponseData getIdVerificationResponseData() {
        return idVerificationResponseData;
    }

    /**
     * Sets the value of the idVerificationResponseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdVerificationResponseData }
     *     
     */
    public void setIdVerificationResponseData(IdVerificationResponseData value) {
        this.idVerificationResponseData = value;
    }

    /**
     * Gets the value of the schufaResponseData property.
     * 
     * @return
     *     possible object is
     *     {@link SchufaResponseData }
     *     
     */
    public SchufaResponseData getSchufaResponseData() {
        return schufaResponseData;
    }

    /**
     * Sets the value of the schufaResponseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchufaResponseData }
     *     
     */
    public void setSchufaResponseData(SchufaResponseData value) {
        this.schufaResponseData = value;
    }

    /**
     * Gets the value of the controlPersons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controlPersons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControlPersons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressDescription }
     * 
     * 
     */
    public List<AddressDescription> getControlPersons() {
        if (controlPersons == null) {
            controlPersons = new ArrayList<AddressDescription>();
        }
        return this.controlPersons;
    }

    /**
     * Gets the value of the controlPersonsExt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controlPersonsExt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControlPersonsExt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControlPerson }
     * 
     * 
     */
    public List<ControlPerson> getControlPersonsExt() {
        if (controlPersonsExt == null) {
            controlPersonsExt = new ArrayList<ControlPerson>();
        }
        return this.controlPersonsExt;
    }

}
