//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * SchufaIdentification element
 * 
 * <p>Java class for SchufaIdentification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SchufaIdentification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identityReservationPerson" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="identityReservationAddress" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="personWithoutBirthdate" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SchufaIdentification", propOrder = {
    "identityReservationPerson",
    "identityReservationAddress",
    "personWithoutBirthdate"
})
public class SchufaIdentification {

    protected boolean identityReservationPerson;
    protected boolean identityReservationAddress;
    protected boolean personWithoutBirthdate;

    /**
     * Gets the value of the identityReservationPerson property.
     * 
     */
    public boolean isIdentityReservationPerson() {
        return identityReservationPerson;
    }

    /**
     * Sets the value of the identityReservationPerson property.
     * 
     */
    public void setIdentityReservationPerson(boolean value) {
        this.identityReservationPerson = value;
    }

    /**
     * Gets the value of the identityReservationAddress property.
     * 
     */
    public boolean isIdentityReservationAddress() {
        return identityReservationAddress;
    }

    /**
     * Sets the value of the identityReservationAddress property.
     * 
     */
    public void setIdentityReservationAddress(boolean value) {
        this.identityReservationAddress = value;
    }

    /**
     * Gets the value of the personWithoutBirthdate property.
     * 
     */
    public boolean isPersonWithoutBirthdate() {
        return personWithoutBirthdate;
    }

    /**
     * Sets the value of the personWithoutBirthdate property.
     * 
     */
    public void setPersonWithoutBirthdate(boolean value) {
        this.personWithoutBirthdate = value;
    }

}
