//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * ScoreDecisionRange element
 * 
 * <p>Java class for ScoreDecisionRange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScoreDecisionRange"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="scoreRange" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Range"/&gt;
 *         &lt;element name="decision" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Decision"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScoreDecisionRange", propOrder = {
    "scoreRange",
    "decision"
})
public class ScoreDecisionRange {

    @XmlElement(required = true)
    protected Range scoreRange;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Decision decision;

    /**
     * Gets the value of the scoreRange property.
     * 
     * @return
     *     possible object is
     *     {@link Range }
     *     
     */
    public Range getScoreRange() {
        return scoreRange;
    }

    /**
     * Sets the value of the scoreRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Range }
     *     
     */
    public void setScoreRange(Range value) {
        this.scoreRange = value;
    }

    /**
     * Gets the value of the decision property.
     * 
     * @return
     *     possible object is
     *     {@link Decision }
     *     
     */
    public Decision getDecision() {
        return decision;
    }

    /**
     * Sets the value of the decision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Decision }
     *     
     */
    public void setDecision(Decision value) {
        this.decision = value;
    }

}
