//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * GetReport request root element
 * 
 * <p>Java class for TypeBaseResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeBaseResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="archivingId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeBaseResponse", propOrder = {
    "archivingId"
})
@XmlSeeAlso({
    TypeIdentifyAddressResponse.class,
    TypeAddressInvestigationResponse.class,
    TypeGetReportResponse.class,
    TypeGetArchivedReportResponse.class,
    TypeGetDebtDetailsResponse.class,
    TypeOrderOfflineReportResponse.class,
    TypeGetListOfReadyOfflineReportsResponse.class,
    TypePollOfflineReportResponseResponse.class,
    TypeIdVerificationResponse.class,
    TypeSubmitDataIssueResponse.class,
    TypeCancelDataIssueResponse.class,
    TypeGetDataIssueStatusResponse.class,
    TypeCreateJobESchKgResponse.class,
    TypeGetStatusESchKgResponse.class,
    TypeGetLastDocumentESchKgResponse.class,
    TypeGetWebAccessTokenESchKgResponse.class,
    TypeCheckOfflineReportOfficeResponse.class
})
public class TypeBaseResponse {

    protected Long archivingId;

    /**
     * Gets the value of the archivingId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getArchivingId() {
        return archivingId;
    }

    /**
     * Sets the value of the archivingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setArchivingId(Long value) {
        this.archivingId = value;
    }

}
