//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * TypeOrderOfflineReportRequest request root element
 * 
 * <p>Java class for TypeOrderOfflineReportRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeOrderOfflineReportRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}TypeBaseRequest"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="orderAddress" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}AddressDescription" minOccurs="0"/&gt;
 *         &lt;element name="identifier" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Identifier" minOccurs="0"/&gt;
 *         &lt;element name="offlineReportType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="binaryPOI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="binaryPOIType" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}PoiType" minOccurs="0"/&gt;
 *         &lt;element name="additionalInput" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}KeyValuePair" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="contactMail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="contactPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeOrderOfflineReportRequest", propOrder = {
    "orderAddress",
    "identifier",
    "offlineReportType",
    "binaryPOI",
    "binaryPOIType",
    "additionalInput",
    "contactMail",
    "contactPhone"
})
public class TypeOrderOfflineReportRequest
    extends TypeBaseRequest
{

    protected AddressDescription orderAddress;
    protected Identifier identifier;
    @XmlElement(required = true)
    protected String offlineReportType;
    protected String binaryPOI;
    @XmlSchemaType(name = "string")
    protected PoiType binaryPOIType;
    protected List<KeyValuePair> additionalInput;
    protected String contactMail;
    protected String contactPhone;

    /**
     * Gets the value of the orderAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDescription }
     *     
     */
    public AddressDescription getOrderAddress() {
        return orderAddress;
    }

    /**
     * Sets the value of the orderAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDescription }
     *     
     */
    public void setOrderAddress(AddressDescription value) {
        this.orderAddress = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setIdentifier(Identifier value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the offlineReportType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfflineReportType() {
        return offlineReportType;
    }

    /**
     * Sets the value of the offlineReportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfflineReportType(String value) {
        this.offlineReportType = value;
    }

    /**
     * Gets the value of the binaryPOI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBinaryPOI() {
        return binaryPOI;
    }

    /**
     * Sets the value of the binaryPOI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinaryPOI(String value) {
        this.binaryPOI = value;
    }

    /**
     * Gets the value of the binaryPOIType property.
     * 
     * @return
     *     possible object is
     *     {@link PoiType }
     *     
     */
    public PoiType getBinaryPOIType() {
        return binaryPOIType;
    }

    /**
     * Sets the value of the binaryPOIType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoiType }
     *     
     */
    public void setBinaryPOIType(PoiType value) {
        this.binaryPOIType = value;
    }

    /**
     * Gets the value of the additionalInput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyValuePair }
     * 
     * 
     */
    public List<KeyValuePair> getAdditionalInput() {
        if (additionalInput == null) {
            additionalInput = new ArrayList<KeyValuePair>();
        }
        return this.additionalInput;
    }

    /**
     * Gets the value of the contactMail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactMail() {
        return contactMail;
    }

    /**
     * Sets the value of the contactMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactMail(String value) {
        this.contactMail = value;
    }

    /**
     * Gets the value of the contactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * Sets the value of the contactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPhone(String value) {
        this.contactPhone = value;
    }

}
