//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * TypeSubmitDataIssueResponse root element
 * 
 * <p>Java class for TypeSubmitDataIssueResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeSubmitDataIssueResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}TypeBaseResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="issueReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="additionalOutput" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}KeyValuePair" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeSubmitDataIssueResponse", propOrder = {
    "issueReference",
    "additionalOutput"
})
public class TypeSubmitDataIssueResponse
    extends TypeBaseResponse
{

    @XmlElement(required = true)
    protected String issueReference;
    protected List<KeyValuePair> additionalOutput;

    /**
     * Gets the value of the issueReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueReference() {
        return issueReference;
    }

    /**
     * Sets the value of the issueReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueReference(String value) {
        this.issueReference = value;
    }

    /**
     * Gets the value of the additionalOutput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalOutput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalOutput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyValuePair }
     * 
     * 
     */
    public List<KeyValuePair> getAdditionalOutput() {
        if (additionalOutput == null) {
            additionalOutput = new ArrayList<KeyValuePair>();
        }
        return this.additionalOutput;
    }

}
