//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;


/**
 * GetReport request root element
 * 
 * <p>Java class for TypeGetReportRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeGetReportRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}TypeBaseRequest"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="searchedAddress" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}AddressDescription" minOccurs="0"/&gt;
 *         &lt;element name="identifier" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Identifier" minOccurs="0"/&gt;
 *         &lt;element name="reportType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="targetReportFormat" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}TargetReportFormat" minOccurs="0"/&gt;
 *         &lt;element name="idVerificationRequestData" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}IdVerificationRequestData" minOccurs="0"/&gt;
 *         &lt;element name="additionalInput" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}KeyValuePair" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeGetReportRequest", propOrder = {
    "searchedAddress",
    "identifier",
    "reportType",
    "targetReportFormat",
    "idVerificationRequestData",
    "additionalInput"
})
@XmlRootElement
public class TypeGetReportRequest
    extends TypeBaseRequest
{

    protected AddressDescription searchedAddress;
    protected Identifier identifier;
    @XmlElement(required = true)
    protected String reportType;
    @XmlSchemaType(name = "string")
    protected TargetReportFormat targetReportFormat;
    protected IdVerificationRequestData idVerificationRequestData;
    protected List<KeyValuePair> additionalInput;

    /**
     * Gets the value of the searchedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDescription }
     *     
     */
    public AddressDescription getSearchedAddress() {
        return searchedAddress;
    }

    /**
     * Sets the value of the searchedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDescription }
     *     
     */
    public void setSearchedAddress(AddressDescription value) {
        this.searchedAddress = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setIdentifier(Identifier value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the reportType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * Sets the value of the reportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportType(String value) {
        this.reportType = value;
    }

    /**
     * Gets the value of the targetReportFormat property.
     * 
     * @return
     *     possible object is
     *     {@link TargetReportFormat }
     *     
     */
    public TargetReportFormat getTargetReportFormat() {
        return targetReportFormat;
    }

    /**
     * Sets the value of the targetReportFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetReportFormat }
     *     
     */
    public void setTargetReportFormat(TargetReportFormat value) {
        this.targetReportFormat = value;
    }

    /**
     * Gets the value of the idVerificationRequestData property.
     * 
     * @return
     *     possible object is
     *     {@link IdVerificationRequestData }
     *     
     */
    public IdVerificationRequestData getIdVerificationRequestData() {
        return idVerificationRequestData;
    }

    /**
     * Sets the value of the idVerificationRequestData property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdVerificationRequestData }
     *     
     */
    public void setIdVerificationRequestData(IdVerificationRequestData value) {
        this.idVerificationRequestData = value;
    }

    /**
     * Gets the value of the additionalInput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyValuePair }
     * 
     * 
     */
    public List<KeyValuePair> getAdditionalInput() {
        if (additionalInput == null) {
            additionalInput = new ArrayList<KeyValuePair>();
        }
        return this.additionalInput;
    }

}
