//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * AddressInvestigationRequest request root element
 * 
 * <p>Java class for TypeAddressInvestigationRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeAddressInvestigationRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}TypeBaseRequest"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identifier" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}Identifier" minOccurs="0"/&gt;
 *         &lt;element name="searchedAddress" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}AddressDescription" minOccurs="0"/&gt;
 *         &lt;element name="targetReportFormat" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}TargetReportFormat" minOccurs="0"/&gt;
 *         &lt;element name="requestHighestDeliverableAddress" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="requestHouseholdAddresses" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="requestKnownAddresses" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="additionalInput" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}KeyValuePair" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeAddressInvestigationRequest", propOrder = {
    "identifier",
    "searchedAddress",
    "targetReportFormat",
    "requestHighestDeliverableAddress",
    "requestHouseholdAddresses",
    "requestKnownAddresses",
    "additionalInput"
})
public class TypeAddressInvestigationRequest
    extends TypeBaseRequest
{

    protected Identifier identifier;
    protected AddressDescription searchedAddress;
    @XmlSchemaType(name = "string")
    protected TargetReportFormat targetReportFormat;
    protected Boolean requestHighestDeliverableAddress;
    protected Boolean requestHouseholdAddresses;
    protected Boolean requestKnownAddresses;
    protected List<KeyValuePair> additionalInput;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setIdentifier(Identifier value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the searchedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDescription }
     *     
     */
    public AddressDescription getSearchedAddress() {
        return searchedAddress;
    }

    /**
     * Sets the value of the searchedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDescription }
     *     
     */
    public void setSearchedAddress(AddressDescription value) {
        this.searchedAddress = value;
    }

    /**
     * Gets the value of the targetReportFormat property.
     * 
     * @return
     *     possible object is
     *     {@link TargetReportFormat }
     *     
     */
    public TargetReportFormat getTargetReportFormat() {
        return targetReportFormat;
    }

    /**
     * Sets the value of the targetReportFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetReportFormat }
     *     
     */
    public void setTargetReportFormat(TargetReportFormat value) {
        this.targetReportFormat = value;
    }

    /**
     * Gets the value of the requestHighestDeliverableAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequestHighestDeliverableAddress() {
        return requestHighestDeliverableAddress;
    }

    /**
     * Sets the value of the requestHighestDeliverableAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequestHighestDeliverableAddress(Boolean value) {
        this.requestHighestDeliverableAddress = value;
    }

    /**
     * Gets the value of the requestHouseholdAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequestHouseholdAddresses() {
        return requestHouseholdAddresses;
    }

    /**
     * Sets the value of the requestHouseholdAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequestHouseholdAddresses(Boolean value) {
        this.requestHouseholdAddresses = value;
    }

    /**
     * Gets the value of the requestKnownAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequestKnownAddresses() {
        return requestKnownAddresses;
    }

    /**
     * Sets the value of the requestKnownAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequestKnownAddresses(Boolean value) {
        this.requestKnownAddresses = value;
    }

    /**
     * Gets the value of the additionalInput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyValuePair }
     * 
     * 
     */
    public List<KeyValuePair> getAdditionalInput() {
        if (additionalInput == null) {
            additionalInput = new ArrayList<KeyValuePair>();
        }
        return this.additionalInput;
    }

}
