//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 11:30:43 AM IST 
//


package com.example.demo.schemas.crip;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * TypePollOfflineReportResponseResponse root element
 * 
 * <p>Java class for TypePollOfflineReportResponseResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypePollOfflineReportResponseResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}TypeBaseResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="offlineReportStatus" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}OfflineReportStatus" minOccurs="0"/&gt;
 *         &lt;element name="report" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="debts" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}DebtEntry" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="offlineReportIdentifier" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}OfflineReportIdentifier" minOccurs="0"/&gt;
 *         &lt;element name="additionalOutput" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}KeyValuePair" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="rejectionReason" type="{http://www.crif-online.ch/webservices/crifsoapservice/v1.00}OfflineReportRejectionReason" minOccurs="0"/&gt;
 *         &lt;element name="numberOfOriginalDocuments" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypePollOfflineReportResponseResponse", propOrder = {
    "offlineReportStatus",
    "report",
    "debts",
    "offlineReportIdentifier",
    "additionalOutput",
    "rejectionReason",
    "numberOfOriginalDocuments"
})
public class TypePollOfflineReportResponseResponse
    extends TypeBaseResponse
{

    @XmlSchemaType(name = "string")
    protected OfflineReportStatus offlineReportStatus;
    protected String report;
    protected List<DebtEntry> debts;
    protected OfflineReportIdentifier offlineReportIdentifier;
    protected List<KeyValuePair> additionalOutput;
    @XmlSchemaType(name = "string")
    protected OfflineReportRejectionReason rejectionReason;
    protected BigInteger numberOfOriginalDocuments;

    /**
     * Gets the value of the offlineReportStatus property.
     * 
     * @return
     *     possible object is
     *     {@link OfflineReportStatus }
     *     
     */
    public OfflineReportStatus getOfflineReportStatus() {
        return offlineReportStatus;
    }

    /**
     * Sets the value of the offlineReportStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfflineReportStatus }
     *     
     */
    public void setOfflineReportStatus(OfflineReportStatus value) {
        this.offlineReportStatus = value;
    }

    /**
     * Gets the value of the report property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReport(String value) {
        this.report = value;
    }

    /**
     * Gets the value of the debts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the debts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDebts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DebtEntry }
     * 
     * 
     */
    public List<DebtEntry> getDebts() {
        if (debts == null) {
            debts = new ArrayList<DebtEntry>();
        }
        return this.debts;
    }

    /**
     * Gets the value of the offlineReportIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link OfflineReportIdentifier }
     *     
     */
    public OfflineReportIdentifier getOfflineReportIdentifier() {
        return offlineReportIdentifier;
    }

    /**
     * Sets the value of the offlineReportIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfflineReportIdentifier }
     *     
     */
    public void setOfflineReportIdentifier(OfflineReportIdentifier value) {
        this.offlineReportIdentifier = value;
    }

    /**
     * Gets the value of the additionalOutput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalOutput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalOutput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyValuePair }
     * 
     * 
     */
    public List<KeyValuePair> getAdditionalOutput() {
        if (additionalOutput == null) {
            additionalOutput = new ArrayList<KeyValuePair>();
        }
        return this.additionalOutput;
    }

    /**
     * Gets the value of the rejectionReason property.
     * 
     * @return
     *     possible object is
     *     {@link OfflineReportRejectionReason }
     *     
     */
    public OfflineReportRejectionReason getRejectionReason() {
        return rejectionReason;
    }

    /**
     * Sets the value of the rejectionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfflineReportRejectionReason }
     *     
     */
    public void setRejectionReason(OfflineReportRejectionReason value) {
        this.rejectionReason = value;
    }

    /**
     * Gets the value of the numberOfOriginalDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfOriginalDocuments() {
        return numberOfOriginalDocuments;
    }

    /**
     * Sets the value of the numberOfOriginalDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfOriginalDocuments(BigInteger value) {
        this.numberOfOriginalDocuments = value;
    }

}
